"""Complete working translations for the explicit composite intake.

Canonical field names, scientific symbols, units and command words are not
translated. These labels are not independent scientific/native-language review.
"""

LABELS = {
    "en": {
        "title": "Two-phase composite intake · v0.28",
        "notice": "Scientific wording (including English) and translations are machine-assisted and have not received independent scientific or native-language review.",
        "scope": "Supply a conditional model, not a material certification. Names do not load properties or establish isotropy. Known unsupported conditions remain recorded; do not change true conditions just to obtain a calculation.",
        "navigation": "Commands: /back = previous field, /cancel = discard and quit. At review: /edit N = edit field N; /save = confirm for local saving. No files are written by this wizard. Blank observations mean unknown, never a default.",
        "import_guidance": "For an existing valid literature_model JSON file, use materials-boundaries composite report case.json --output case-report. Its model_evidence is preserved. A generic E/ν editor is deferred: this wizard accepts K and G only and does not invent conversion evidence or citations.",
        "tty_required": "Interactive intake requires terminal (TTY) input and output; use blank initialization or an explicit original demo for non-interactive use.",
        "cancelled": "Intake cancelled; no case was saved.",
        "first_field": "Already at the first field; use /cancel to discard the draft.",
        "case_id": "Case ID (required)",
        "origin": "Input origin: 1 = hypothetical model; 2 = user-supplied phase data (choose explicitly)",
        "user_origin": "Claimed origin of user data: 1 = measured; 2 = unspecified (choose explicitly). A paper or citation does not establish measurement.",
        "origin_warning": "Provenance is a supplied claim. Selecting measured does not verify a specimen; hypothetical values and conditions are supplied model assumptions.",
        "phase_id": "Phase {phase} ID (required and unique)",
        "fraction": "Phase {phase} fraction",
        "basis": "Phase {phase} fraction basis: 1 = volume; 2 = mass (unsupported); 3 or blank = unknown",
        "fraction_value": "Phase {phase} volume fraction [0, 1], or blank/unknown",
        "mass_unsupported": "Mass fractions are unsupported. No density inference or conversion is available. Supply a known volume fraction, or select unknown; no complement is calculated.",
        "bulk": "Phase {phase} K: number and unit (Pa/kPa/MPa/GPa), or blank/unknown",
        "shear": "Phase {phase} G: number and unit (Pa/kPa/MPa/GPa), or blank/unknown",
        "quantity_notice": "Use explicit K/G units, for example 12 GPa. Zero/negative known values are retained as supplied; the runtime may find them outside its supported positive-modulus domain.",
        "condition": "{field}: 1 = known supported value {expected}; 2 = known different value; 3 or blank = unknown (no preselection)",
        "other_condition": "{field}: enter the known different canonical value, or blank/unknown",
        "condition_basis": "All selected conditions are supplied assertions/assumptions, not independently established specimen evidence.",
        "sources": "Source IDs, comma-separated; blank = none. IDs are user citations and may remain unresolved; no lookup or evidence upgrade occurs",
        "note": "Provenance note in your own words; blank = no note",
        "review": "Review the complete draft",
        "review_notice": "Check every value, unit, source ID, condition and unknown below. No physical verification or independent scientific review is implied. Confirmation is required before the caller can save locally.",
        "field": "Field",
        "stored": "Stored value",
        "review_action": "Enter /save to confirm, /edit N to edit, /back to revisit the last field, or /cancel to discard",
        "edit_prompt": "Field number to edit, or /back to return to review",
        "required": "Enter a nonempty value; there is no default.",
        "choice_required": "Choose one of the displayed options explicitly; there is no default.",
        "choice_invalid": "Choose one of the displayed options, or blank/unknown where offered.",
        "duplicate_id": "Phase IDs must be unique; this ID is already used by the other phase.",
        "number_invalid": "Enter a finite JSON number. Boolean values, nonfinite numbers, out-of-range numbers and nonzero underflow are rejected.",
        "fraction_range": "A volume fraction must be between 0 and 1, or unknown.",
        "quantity_invalid": "Enter a number followed by one canonical unit: Pa, kPa, MPa or GPa. Blank/unknown leaves the entire quantity unknown.",
        "dimension_invalid": "The known dimension must be a positive integer, or unknown.",
        "different_required": "This is the supported value. Select option 1 to assert it explicitly, or enter a genuinely different value.",
        "sources_invalid": "Each comma-separated source ID must be nonempty; blank alone means no source IDs.",
        "edit_invalid": "Choose a field number from the displayed review list.",
        "review_invalid": "The draft is not structurally valid; edit the indicated fields before confirming.",
        "fraction_exceed": "The known volume fractions exceed 1 (absolute tolerance 1e-12). Edit the fractions; neither is silently changed.",
        "fraction_sum": "Both known volume fractions must sum to 1 (absolute tolerance 1e-12). Edit them, or explicitly mark a missing observation unknown; no complement is inferred.",
        "cannot_save": "This draft cannot be confirmed until the structural error is corrected.",
        "unknown": "Unknown",
    },
    "zh": {
        "title": "双相复合材料输入 · v0.28",
        "notice": "科学表述（包括英文）及翻译由机器辅助，尚未经独立科学审查或母语审校。",
        "scope": "输入的是有条件的模型，不是材料认证。材料名称不会自动载入属性或证明各向同性。已知的不支持条件仍会保留；请勿仅为获得计算结果而改变真实条件。",
        "navigation": "命令：/back = 上一个字段；/cancel = 丢弃并退出。复核时：/edit N = 编辑第 N 个字段；/save = 确认供本地保存。本向导不写入文件。观测值留空表示未知，绝不是默认值。",
        "import_guidance": "已有有效的 literature_model JSON 文件时，请使用 materials-boundaries composite report case.json --output case-report。其 model_evidence 会被保留。通用 E/ν 编辑器尚未提供：本向导仅接受 K 和 G，不会编造换算证据或引文。",
        "tty_required": "交互输入需要终端（TTY）输入和输出；非交互使用请创建空白实例或明确选择原创新示例。",
        "cancelled": "已取消输入；没有保存案例。",
        "first_field": "已是第一个字段；使用 /cancel 丢弃草稿。",
        "case_id": "案例 ID（必填）",
        "origin": "输入来源：1 = 假设模型；2 = 用户提供的相数据（请明确选择）",
        "user_origin": "用户声明的数据来源：1 = 测量；2 = 未说明（请明确选择）。论文或引文不等于测量证据。",
        "origin_warning": "来源类型只是用户声明。选择测量不会验证试样；假设值和条件属于用户提供的模型假设。",
        "phase_id": "第 {phase} 相 ID（必填且唯一）",
        "fraction": "第 {phase} 相分数",
        "basis": "第 {phase} 相分数的基准：1 = 体积；2 = 质量（不支持）；3 或留空 = 未知",
        "fraction_value": "第 {phase} 相体积分数 [0, 1]，或留空/unknown",
        "mass_unsupported": "不支持质量分数，也不推断密度或进行换算。请提供已知体积分数，或选择未知；不会自动计算另一相的补足分数。",
        "bulk": "第 {phase} 相 K：数值和单位（Pa/kPa/MPa/GPa），或留空/unknown",
        "shear": "第 {phase} 相 G：数值和单位（Pa/kPa/MPa/GPa），或留空/unknown",
        "quantity_notice": "请明确填写 K/G 单位，例如 12 GPa。已知的零值或负值将按原样保留；程序可能将其判定为不属于所支持的正模量范围。",
        "condition": "{field}：1 = 已知且符合支持值 {expected}；2 = 已知不同值；3 或留空 = 未知（无预选）",
        "other_condition": "{field}：输入已知的不同规范值，或留空/unknown",
        "condition_basis": "所有选定条件都是用户提供的声明/假设，不是独立确立的试样证据。",
        "sources": "来源 ID，用逗号分隔；留空 = 无。ID 是用户引文，可能无法解析；不会检索或提升证据等级",
        "note": "用自己的话填写来源说明；留空 = 无说明",
        "review": "复核完整草稿",
        "review_notice": "请检查下方每个数值、单位、来源 ID、条件和未知项。这不意味着物理验证或独立科学审查。调用方仅在明确确认后才能在本地保存。",
        "field": "字段",
        "stored": "已存草稿值",
        "review_action": "输入 /save 确认、/edit N 编辑、/back 返回最后一个字段，或 /cancel 丢弃",
        "edit_prompt": "输入要编辑的字段编号，或 /back 返回复核",
        "required": "请输入非空值；没有默认值。",
        "choice_required": "请明确选择所列选项之一；没有默认值。",
        "choice_invalid": "请选择所列选项之一，或在允许时留空/unknown。",
        "duplicate_id": "相 ID 必须唯一；另一相已使用此 ID。",
        "number_invalid": "请输入有限的 JSON 数值。不接受布尔值、非有限数、超出范围的数或非零下溢数。",
        "fraction_range": "体积分数必须在 0 到 1 之间，或为未知。",
        "quantity_invalid": "请输入数值及一个规范单位：Pa、kPa、MPa 或 GPa。留空/unknown 表示整个量未知。",
        "dimension_invalid": "已知维数必须是正整数，或为未知。",
        "different_required": "这正是支持值。请选择选项 1 明确声明该值，或输入确实不同的值。",
        "sources_invalid": "每个逗号分隔的来源 ID 都必须非空；整项留空表示无来源 ID。",
        "edit_invalid": "请选择复核列表中显示的字段编号。",
        "review_invalid": "草稿结构无效；确认前请编辑所指出的字段。",
        "fraction_exceed": "已知体积分数之和超过 1（绝对容差 1e-12）。请编辑分数；不会自动改变任一分数。",
        "fraction_sum": "两个已知体积分数之和必须为 1（绝对容差 1e-12）。请编辑，或明确将缺失观测标为未知；不会推断补足分数。",
        "cannot_save": "必须纠正结构错误后才能确认草稿。",
        "unknown": "未知",
    },
    "ja": {
        "title": "二相複合材料の入力 · v0.28",
        "notice": "科学的表現（英語を含む）と翻訳は機械支援によるもので、独立した科学的審査や母語話者による校閲を受けていません。",
        "scope": "入力するのは条件付きモデルであり、材料の認証ではありません。名称から物性値や等方性を推定しません。既知の非対応条件も保存します。計算結果を得るためだけに実際の条件を変更しないでください。",
        "navigation": "コマンド：/back = 前の項目、/cancel = 破棄して終了。確認時：/edit N = 項目 N を編集、/save = ローカル保存用に確定。このウィザード自体はファイルを書き込みません。観測値の空欄は不明を意味し、既定値ではありません。",
        "import_guidance": "有効な literature_model JSON ファイルがある場合は materials-boundaries composite report case.json --output case-report を使用してください。model_evidence は保持されます。汎用 E/ν エディターは未対応です。このウィザードは K と G のみを受け付け、変換の根拠や引用を作りません。",
        "tty_required": "対話入力には端末（TTY）の入力と出力が必要です。非対話では空のインスタンス、または明示的に選んだ独自の仮想例を使用してください。",
        "cancelled": "入力を取り消しました。ケースは保存されていません。",
        "first_field": "最初の項目です。草稿を破棄するには /cancel を使用してください。",
        "case_id": "ケース ID（必須）",
        "origin": "入力の出所：1 = 仮想モデル、2 = ユーザー提供の相データ（明示的に選択）",
        "user_origin": "ユーザーが申告するデータの出所：1 = 測定、2 = 未指定（明示的に選択）。論文や引用だけでは測定を立証しません。",
        "origin_warning": "出所はユーザーの申告です。測定を選んでも試料は検証されません。仮想値と条件は、入力されたモデルの仮定です。",
        "phase_id": "相 {phase} の ID（必須・重複不可）",
        "fraction": "相 {phase} の分率",
        "basis": "相 {phase} の分率の基準：1 = 体積、2 = 質量（非対応）、3 または空欄 = 不明",
        "fraction_value": "相 {phase} の体積分率 [0, 1]、または空欄/unknown",
        "mass_unsupported": "質量分率は非対応です。密度の推定や変換は行いません。既知の体積分率を入力するか、不明を選択してください。他方の分率を補完しません。",
        "bulk": "相 {phase} の K：数値と単位（Pa/kPa/MPa/GPa）、または空欄/unknown",
        "shear": "相 {phase} の G：数値と単位（Pa/kPa/MPa/GPa）、または空欄/unknown",
        "quantity_notice": "K/G の単位を明示してください（例：12 GPa）。既知のゼロや負の値も入力どおり保持します。実行時には、対応する正の弾性率の範囲外と判定される場合があります。",
        "condition": "{field}：1 = 対応値 {expected} であることが既知、2 = 別の値が既知、3 または空欄 = 不明（事前選択なし）",
        "other_condition": "{field}：既知の異なる標準値、または空欄/unknown を入力",
        "condition_basis": "選択した条件はすべて入力された主張・仮定であり、独立に確立された試料の証拠ではありません。",
        "sources": "出典 ID をコンマ区切りで入力。空欄 = なし。ID はユーザーの引用であり、未解決のままの場合があります。検索や証拠の格上げは行いません",
        "note": "出所について自分の言葉で記入。空欄 = 注記なし",
        "review": "草稿全体の確認",
        "review_notice": "以下のすべての値、単位、出典 ID、条件、不明項目を確認してください。物理的検証や独立した科学的審査を意味しません。呼び出し側がローカル保存する前に明示的な確定が必要です。",
        "field": "項目",
        "stored": "草稿の保存値",
        "review_action": "/save で確定、/edit N で編集、/back で最後の項目に戻る、/cancel で破棄",
        "edit_prompt": "編集する項目番号、または /back で確認に戻る",
        "required": "空でない値を入力してください。既定値はありません。",
        "choice_required": "表示された選択肢を明示的に選んでください。既定値はありません。",
        "choice_invalid": "表示された選択肢、または許可されている場合は空欄/unknown を選んでください。",
        "duplicate_id": "相 ID は重複できません。この ID はもう一方の相が使用しています。",
        "number_invalid": "有限の JSON 数値を入力してください。真偽値、非有限値、範囲外の数値、非ゼロのアンダーフローは受け付けません。",
        "fraction_range": "体積分率は 0 から 1 の範囲、または不明である必要があります。",
        "quantity_invalid": "数値に続けて標準単位 Pa、kPa、MPa、GPa のいずれかを入力してください。空欄/unknown は量全体を不明にします。",
        "dimension_invalid": "既知の次元は正の整数、または不明である必要があります。",
        "different_required": "これは対応値です。選択肢 1 で明示的に申告するか、本当に異なる値を入力してください。",
        "sources_invalid": "コンマで区切った各出典 ID は空にできません。全体の空欄は出典 ID なしを意味します。",
        "edit_invalid": "確認リストに表示された項目番号を選んでください。",
        "review_invalid": "草稿の構造が無効です。確定する前に該当項目を編集してください。",
        "fraction_exceed": "既知の体積分率の合計が 1 を超えています（絶対許容差 1e-12）。分率を編集してください。どちらも自動変更しません。",
        "fraction_sum": "両方が既知の体積分率の合計は 1 である必要があります（絶対許容差 1e-12）。編集するか、欠けた観測値を明示的に不明にしてください。補完は推定しません。",
        "cannot_save": "構造上の誤りを修正するまで草稿を確定できません。",
        "unknown": "不明",
    },
    "de": {
        "title": "Eingabe eines Zweiphasenverbunds · v0.28",
        "notice": "Wissenschaftliche Formulierungen (auch auf Englisch) und Übersetzungen sind maschinell unterstützt und weder unabhängig wissenschaftlich noch muttersprachlich geprüft.",
        "scope": "Sie geben ein bedingtes Modell ein, keine Materialzertifizierung. Namen laden keine Eigenschaften und belegen keine Isotropie. Bekannte nicht unterstützte Bedingungen bleiben erhalten; ändern Sie wahre Bedingungen nicht nur, um eine Berechnung zu erhalten.",
        "navigation": "Befehle: /back = voriges Feld; /cancel = verwerfen und beenden. Bei der Prüfung: /edit N = Feld N bearbeiten; /save = zur lokalen Speicherung bestätigen. Dieser Assistent schreibt keine Dateien. Leere Beobachtungen bedeuten unbekannt, niemals einen Vorgabewert.",
        "import_guidance": "Für eine vorhandene gültige literature_model-JSON-Datei verwenden Sie materials-boundaries composite report case.json --output case-report. model_evidence bleibt erhalten. Ein allgemeiner E/ν-Editor ist zurückgestellt: Dieser Assistent akzeptiert nur K und G und erfindet keine Umrechnungsbelege oder Quellen.",
        "tty_required": "Interaktive Eingabe erfordert Terminal-Ein- und -Ausgabe (TTY). Nutzen Sie nicht interaktiv eine leere Vorlage oder ein ausdrücklich gewähltes ursprüngliches fiktives Beispiel.",
        "cancelled": "Eingabe abgebrochen; kein Fall wurde gespeichert.",
        "first_field": "Sie sind bereits beim ersten Feld; mit /cancel verwerfen Sie den Entwurf.",
        "case_id": "Fall-ID (erforderlich)",
        "origin": "Eingabeherkunft: 1 = hypothetisches Modell; 2 = vom Benutzer gelieferte Phasendaten (ausdrücklich wählen)",
        "user_origin": "Angegebene Herkunft der Benutzerdaten: 1 = gemessen; 2 = nicht angegeben (ausdrücklich wählen). Eine Veröffentlichung oder Quellenangabe belegt keine Messung.",
        "origin_warning": "Die Herkunft ist eine Benutzerangabe. Die Auswahl gemessen überprüft keine Probe; hypothetische Werte und Bedingungen sind angegebene Modellannahmen.",
        "phase_id": "ID von Phase {phase} (erforderlich und eindeutig)",
        "fraction": "Anteil von Phase {phase}",
        "basis": "Bezugsbasis für Phase {phase}: 1 = Volumen; 2 = Masse (nicht unterstützt); 3 oder leer = unbekannt",
        "fraction_value": "Volumenanteil von Phase {phase} [0, 1], oder leer/unknown",
        "mass_unsupported": "Massenanteile werden nicht unterstützt. Dichte wird weder erschlossen noch zur Umrechnung verwendet. Geben Sie einen bekannten Volumenanteil an oder wählen Sie unbekannt; der andere Anteil wird nicht ergänzt.",
        "bulk": "K von Phase {phase}: Zahl und Einheit (Pa/kPa/MPa/GPa), oder leer/unknown",
        "shear": "G von Phase {phase}: Zahl und Einheit (Pa/kPa/MPa/GPa), oder leer/unknown",
        "quantity_notice": "Geben Sie K/G-Einheiten ausdrücklich an, etwa 12 GPa. Bekannte Null- oder Negativwerte bleiben erhalten; die Laufzeit kann sie als außerhalb des unterstützten Bereichs positiver Moduln einstufen.",
        "condition": "{field}: 1 = bekannter unterstützter Wert {expected}; 2 = bekannter anderer Wert; 3 oder leer = unbekannt (keine Vorauswahl)",
        "other_condition": "{field}: bekannten anderen kanonischen Wert eingeben, oder leer/unknown",
        "condition_basis": "Alle gewählten Bedingungen sind angegebene Aussagen/Annahmen, keine unabhängig festgestellten Nachweise über eine Probe.",
        "sources": "Quellen-IDs, durch Kommas getrennt; leer = keine. IDs sind Benutzerzitate und können unaufgelöst bleiben; keine Recherche oder Aufwertung des Nachweisstatus",
        "note": "Herkunftshinweis in eigenen Worten; leer = kein Hinweis",
        "review": "Vollständigen Entwurf prüfen",
        "review_notice": "Prüfen Sie jeden Wert, jede Einheit, Quellen-ID, Bedingung und unbekannte Angabe. Dies bedeutet keine physikalische Überprüfung oder unabhängige wissenschaftliche Prüfung. Vor lokaler Speicherung durch das aufrufende Programm ist Ihre Bestätigung erforderlich.",
        "field": "Feld",
        "stored": "Gespeicherter Entwurfswert",
        "review_action": "/save zum Bestätigen, /edit N zum Bearbeiten, /back zum letzten Feld oder /cancel zum Verwerfen eingeben",
        "edit_prompt": "Nummer des zu bearbeitenden Felds, oder /back zur Prüfung zurück",
        "required": "Geben Sie einen nicht leeren Wert ein; es gibt keine Vorgabe.",
        "choice_required": "Wählen Sie ausdrücklich eine der angezeigten Optionen; es gibt keine Vorgabe.",
        "choice_invalid": "Wählen Sie eine angezeigte Option oder, wo angeboten, leer/unknown.",
        "duplicate_id": "Phasen-IDs müssen eindeutig sein; diese ID wird bereits von der anderen Phase verwendet.",
        "number_invalid": "Geben Sie eine endliche JSON-Zahl ein. Boolesche Werte, nichtendliche Zahlen, Bereichsüberschreitungen und Unterlauf eines Nichtnullwerts werden abgewiesen.",
        "fraction_range": "Ein Volumenanteil muss zwischen 0 und 1 liegen oder unbekannt sein.",
        "quantity_invalid": "Geben Sie eine Zahl gefolgt von einer kanonischen Einheit ein: Pa, kPa, MPa oder GPa. Leer/unknown lässt die gesamte Größe unbekannt.",
        "dimension_invalid": "Eine bekannte Dimension muss eine positive ganze Zahl sein, oder unbekannt bleiben.",
        "different_required": "Dies ist der unterstützte Wert. Wählen Sie Option 1, um ihn ausdrücklich anzugeben, oder geben Sie einen tatsächlich anderen Wert ein.",
        "sources_invalid": "Jede durch Kommas getrennte Quellen-ID muss nicht leer sein; eine vollständig leere Eingabe bedeutet keine Quellen-IDs.",
        "edit_invalid": "Wählen Sie eine Feldnummer aus der angezeigten Prüfliste.",
        "review_invalid": "Der Entwurf ist strukturell ungültig; bearbeiten Sie die betroffenen Felder vor der Bestätigung.",
        "fraction_exceed": "Die bekannten Volumenanteile überschreiten 1 (absolute Toleranz 1e-12). Bearbeiten Sie die Anteile; keiner wird stillschweigend geändert.",
        "fraction_sum": "Zwei bekannte Volumenanteile müssen zusammen 1 ergeben (absolute Toleranz 1e-12). Bearbeiten Sie sie oder kennzeichnen Sie eine fehlende Beobachtung ausdrücklich als unbekannt; keine Ergänzung wird erschlossen.",
        "cannot_save": "Dieser Entwurf kann erst nach Korrektur des Strukturfehlers bestätigt werden.",
        "unknown": "Unbekannt",
    },
}

CONDITION_REASONS = {
    "en": {
        "dimension": "These scalar bounds implement the three-dimensional model; a different dimension needs a different contract.",
        "constituent_symmetry": "Each phase must admit isotropic K and G in the supported model; its name or material class does not establish this.",
        "effective_symmetry": "Isotropic phases do not establish effective isotropy. The composite must separately admit scalar effective K and G.",
        "kinematics": "The model uses infinitesimal strain; finite deformation is outside its implemented assumptions.",
        "constitutive_law": "The elastic bounds require a linear-elastic law; nonlinear or inelastic response is outside this calculation.",
        "loading": "These are static elastic bounds, not a dynamic, rate-dependent or viscoelastic prediction.",
        "interface": "The implemented model assumes perfect bonding; slip, separation or compliant interfaces require another model.",
    },
    "zh": {
        "dimension": "这些标量界实现的是三维模型；其他维数需要不同的模型约定。",
        "constituent_symmetry": "支持模型中的每一相都必须能用各向同性 K 和 G 描述；名称或材料类别不能证明这一点。",
        "effective_symmetry": "各相各向同性并不能证明有效性质各向同性。必须单独确认复合材料可用标量有效 K 和 G 描述。",
        "kinematics": "模型采用无穷小应变；有限变形超出已实现的假设范围。",
        "constitutive_law": "这些弹性界要求线弹性本构关系；非线性或非弹性响应不属于本计算。",
        "loading": "这些是静态弹性界，不是动态、速率相关或黏弹性预测。",
        "interface": "已实现的模型假定完全黏结；滑移、分离或柔性界面需要其他模型。",
    },
    "ja": {
        "dimension": "これらのスカラー上下界は三次元モデルを実装しています。異なる次元には別のモデル定義が必要です。",
        "constituent_symmetry": "対応モデルでは各相を等方性の K と G で表す必要があります。名称や材料分類だけでは立証できません。",
        "effective_symmetry": "各相の等方性は有効特性の等方性を立証しません。複合材料をスカラーの有効 K と G で表せることを別途確認する必要があります。",
        "kinematics": "モデルは微小ひずみを用います。有限変形は実装された仮定の範囲外です。",
        "constitutive_law": "弾性上下界は線形弾性則を必要とします。非線形または非弾性応答は対象外です。",
        "loading": "これは静的弾性の上下界であり、動的、速度依存、粘弾性の予測ではありません。",
        "interface": "実装モデルは完全接着を仮定します。すべり、剥離、柔らかい界面には別のモデルが必要です。",
    },
    "de": {
        "dimension": "Diese skalaren Schranken implementieren das dreidimensionale Modell; andere Dimensionen benötigen einen anderen Modellvertrag.",
        "constituent_symmetry": "Jede Phase muss im unterstützten Modell durch isotrope K und G beschreibbar sein; Name oder Materialklasse belegen dies nicht.",
        "effective_symmetry": "Isotrope Phasen belegen keine effektive Isotropie. Der Verbund muss unabhängig davon skalare effektive K und G zulassen.",
        "kinematics": "Das Modell verwendet infinitesimale Dehnungen; endliche Verformung liegt außerhalb seiner implementierten Annahmen.",
        "constitutive_law": "Die elastischen Schranken verlangen ein linear-elastisches Gesetz; nichtlineare oder inelastische Antworten sind ausgeschlossen.",
        "loading": "Dies sind statische elastische Schranken, keine dynamische, ratenabhängige oder viskoelastische Vorhersage.",
        "interface": "Das implementierte Modell setzt perfekte Bindung voraus; Gleiten, Ablösung oder nachgiebige Grenzflächen erfordern ein anderes Modell.",
    },
}
