"""Authored presentation labels for source-ordered observation inspection.

These working translations describe the catalog's existing interpretation and
limits. They do not translate source passages or supply scientific metadata.
Keep every locale complete; labels must not be filled by English fallbacks.
"""


LABELS = {
    "en": {
        "title": "Observation inspection",
        "subtitle": "Inspection only, in source order; no matched-condition comparison.",
        "policy": "No ranking, aggregation or overlay. Stiffness and strength remain separate quantities; unknown conditions do not establish equivalence.",
        "translation_notice": "Scientific wording and translations are machine-assisted and have not received independent scientific or native-language review.",
        "snapshot_notice": "SHA-256 digests identify the bundled catalog metadata, not the paper bytes. Source records have no individual version field.",
        "rights_notice": "No source PDFs, full text, figures, screenshots or raw measurement data are redistributed. Permission to read a source does not establish permission to reuse it; artifact-specific rights remain applicable.",
        "classification": "Source-reported · experiment-derived · model-dependent · catalog-only",
        "normalized": "Normalized catalog display",
        "normalized_notice": "Exact stored N/m values displayed from the catalog; this display is not a verbatim source quotation.",
        "source_wording": "Original source wording",
        "source_wording_absent": "No source-value wording is stored for this record; no quotation is reconstructed.",
        "original_context": "Original source context may mention three-dimensional units; those are not additional selected results.",
        "identity": "Identity",
        "quantity": "Quantity",
        "study": "Study",
        "record_version": "Record version",
        "uncertainty": "Uncertainty meaning",
        "uncertainty_evidence": "Evidence for uncertainty meaning",
        "statistic": "Central-value statistic",
        "statistic_unknown": "Exact central-statistic label unspecified; do not assume a mean.",
        "sample": "Sample information and count scope",
        "conditions": "Known and unknown conditions",
        "model": "Source inference model",
        "evidence": "Value evidence and source locator",
        "verification": "Inspection and verification scope",
        "rights": "Source rights and reuse limits",
        "details": "Full source and record details",
        "source_links": "Source links",
        "unknown": "Unknown / not established",
        "group_study": "Grouped by study",
        "group_quantity": "Grouped by quantity",
        "record": "Record",
        "source": "Source",
        "catalog_schema": "Catalog schema version",
        "digest": "Metadata snapshot SHA-256",
        "stiffness": "2D in-plane stiffness",
        "strength": "2D breaking strength",
        "no_comparison": "Associated summaries from one study are not independent confirmations. This view establishes no comparability, theoretical bounds or engineering allowables.",
        "command": "Inspect catalog-only experimental observations without evaluating or ranking them",
        "inspect": "Export source-ordered observation inspection views",
        "output": "Output directory for JSON, CSV, SVG and HTML inspection files",
        "ids": "Exact record IDs; repeat the option to select several records",
        "id": "Exact record ID; repeat to select several records",
        "source_filter": "Select records from this exact source ID",
        "source_id": "Exact source ID filter",
        "quantity_filter": "Select one supported two-dimensional quantity",
        "group": "Group navigation by study or quantity; no change in scientific interpretation",
        "group_by": "Group by study or quantity, retaining source order within each group",
        "primary_warning": "Read before interpreting the value",
        "graphene_warning": "The source-reported ± has an unverified statistical meaning. It is not established as SD, SEM, a confidence interval or a hard bound.",
        "mos2_warning": "Source-reported values retain an unresolved printed-q discrepancy: the actual fitted q is unknown, and no refit or correction was performed. Strength also inherits the fitted-stiffness and source-model caveat.",
        "hbn_strength_warning": "Source-reported nonlinear FEM strength is volume-averaged stress beneath the indenter; the exact central-statistic label and stress component are unspecified. It is not uniform-tension strength, a local maximum or the maximum Von Mises stress in Supplementary Figure S5.",
        "hbn_stiffness_warning": "Source-reported stiffness comes from a circular-membrane force–deflection fit. This inference is distinct from the nonlinear FEM strength reduction.",
        "sd_warning": "Reported standard deviation (SD) is not SEM, a confidence interval, 68% coverage, a hard bound or a full uncertainty budget. Averaging and replicate weights, and coverage, are unknown.",
    },
    "zh": {
        "title": "观测记录查阅",
        "subtitle": "仅供查阅，按来源顺序排列；不作同条件比较。",
        "policy": "不排名、不合并、不叠加。刚度与强度仍是不同物理量；条件未知不意味着条件等同。",
        "translation_notice": "科学表述及译文由机器辅助编写，尚未经独立的科学审校或母语审校。",
        "snapshot_notice": "SHA-256 摘要标识所附目录元数据，而非论文文件字节。来源记录没有单独的版本字段。",
        "rights_notice": "不再分发来源 PDF、全文、图件、截图或原始测量数据。可阅读来源不代表获得复用许可；仍须遵守各资料的具体权利限制。",
        "classification": "来源报告 · 实验推导 · 依赖模型 · 仅用于目录",
        "normalized": "规范化目录显示",
        "normalized_notice": "按目录中存储的精确数值以 N/m 显示；此显示不是来源原文的逐字引文。",
        "source_wording": "来源原始表述",
        "source_wording_absent": "此记录未存储来源的数值原文；不据此重构引文。",
        "original_context": "来源原始上下文可能提及三维单位；这些不是额外选入的结果。",
        "identity": "记录标识",
        "quantity": "物理量",
        "study": "研究",
        "record_version": "记录版本",
        "uncertainty": "不确定度含义",
        "uncertainty_evidence": "不确定度含义的依据",
        "statistic": "中心值统计量",
        "statistic_unknown": "中心统计量的确切名称未明确；不得假定为平均值。",
        "sample": "样本信息与计数范围",
        "conditions": "已知与未知条件",
        "model": "来源推断模型",
        "evidence": "数值依据与来源位置",
        "verification": "查阅与核实范围",
        "rights": "来源权利与复用限制",
        "details": "完整来源与记录详情",
        "source_links": "来源链接",
        "unknown": "未知／尚未确定",
        "group_study": "按研究分组",
        "group_quantity": "按物理量分组",
        "record": "记录",
        "source": "来源",
        "catalog_schema": "目录模式版本",
        "digest": "元数据快照 SHA-256",
        "stiffness": "二维面内刚度",
        "strength": "二维断裂强度",
        "no_comparison": "同一研究中相互关联的汇总值不是独立验证。此视图不确立可比性、理论界限或工程许用值。",
        "command": "查阅仅用于目录的实验观测记录，不执行计算或排名",
        "inspect": "导出按来源顺序排列的观测记录查阅视图",
        "output": "JSON、CSV、SVG 和 HTML 查阅文件的输出目录",
        "ids": "精确记录 ID；重复此选项可选择多条记录",
        "id": "精确记录 ID；重复使用可选择多条记录",
        "source_filter": "选择来自此精确来源 ID 的记录",
        "source_id": "精确来源 ID 筛选条件",
        "quantity_filter": "选择一种受支持的二维物理量",
        "group": "按研究或物理量组织导航；不改变科学解释",
        "group_by": "按研究或物理量分组，组内保留来源顺序",
        "primary_warning": "解释数值前请先阅读",
        "graphene_warning": "来源报告的 ± 的统计含义尚未核实。不能将其认定为标准差（SD）、均值标准误（SEM）、置信区间或硬界限。",
        "mos2_warning": "保留来源报告值，其中印出的 q 存在尚未解决的不一致：实际拟合所用的 q 未知，未重新拟合或修正。强度还继承拟合刚度及来源模型的限制。",
        "hbn_strength_warning": "来源报告的非线性有限元强度是压头下方应力的体积平均；中心统计量的确切名称及应力分量未明确。它不是均匀拉伸强度、局部最大值或补充图 S5 中的最大 Von Mises 应力。",
        "hbn_stiffness_warning": "来源报告的刚度来自圆膜力–挠度关系拟合。此推断不同于非线性有限元强度归约。",
        "sd_warning": "报告的标准差（SD）不是均值标准误（SEM）、置信区间、68% 覆盖范围、硬界限或完整不确定度预算。平均方式、重复测量权重及覆盖范围未知。",
    },
    "ja": {
        "title": "観測記録の確認",
        "subtitle": "出典順の確認専用表示です。同一条件での比較は行いません。",
        "policy": "順位付け、集約、重ね合わせは行いません。剛性と強度は別の物理量であり、条件不明は条件の同等性を示しません。",
        "translation_notice": "科学的な記述と翻訳は機械支援で作成しており、独立した科学的査読や母語話者による校閲は受けていません。",
        "snapshot_notice": "SHA-256 ダイジェストは同梱したカタログのメタデータを識別するもので、論文ファイルのバイト列を識別するものではありません。出典記録には個別のバージョン欄がありません。",
        "rights_notice": "出典 PDF、全文、図、スクリーンショット、測定の生データは再配布しません。閲覧できることは再利用の許可を意味せず、各資料の権利条件が適用されます。",
        "classification": "出典の報告値 · 実験から導出 · モデル依存 · カタログ専用",
        "normalized": "正規化したカタログ表示",
        "normalized_notice": "カタログに保存した正確な値を N/m で表示します。この表示は出典の逐語引用ではありません。",
        "source_wording": "出典の原文表記",
        "source_wording_absent": "この記録には値の出典原文を保存していません。引用文を再構成しません。",
        "original_context": "出典原文の文脈には三次元の単位が含まれる場合がありますが、追加の選定結果ではありません。",
        "identity": "識別情報",
        "quantity": "物理量",
        "study": "研究",
        "record_version": "記録のバージョン",
        "uncertainty": "不確かさの意味",
        "uncertainty_evidence": "不確かさの意味を示す根拠",
        "statistic": "中心値の統計量",
        "statistic_unknown": "中心統計量の正確な名称は未指定です。平均値とは仮定しません。",
        "sample": "試料情報と計数の範囲",
        "conditions": "既知・未知の条件",
        "model": "出典の推定モデル",
        "evidence": "値の根拠と出典内の位置",
        "verification": "資料確認と検証の範囲",
        "rights": "出典の権利と再利用の制限",
        "details": "出典と記録の全詳細",
        "source_links": "出典リンク",
        "unknown": "不明／未確立",
        "group_study": "研究別の表示",
        "group_quantity": "物理量別の表示",
        "record": "記録",
        "source": "出典",
        "catalog_schema": "カタログスキーマのバージョン",
        "digest": "メタデータのスナップショット SHA-256",
        "stiffness": "二次元面内剛性",
        "strength": "二次元破断強度",
        "no_comparison": "同じ研究の関連する要約値は独立した検証ではありません。この表示は比較可能性、理論的限界、設計許容値を確立しません。",
        "command": "カタログ専用の実験観測記録を、計算評価や順位付けをせずに確認する",
        "inspect": "出典順の観測記録確認ビューを出力する",
        "output": "JSON、CSV、SVG、HTML の確認用ファイルの出力先ディレクトリ",
        "ids": "正確な記録 ID。このオプションを繰り返すと複数選択できます",
        "id": "正確な記録 ID。繰り返し指定で複数選択できます",
        "source_filter": "指定した正確な出典 ID の記録を選択する",
        "source_id": "正確な出典 ID による絞り込み",
        "quantity_filter": "対応する二次元物理量を一つ選択する",
        "group": "研究または物理量で表示をまとめる。科学的解釈は変わりません",
        "group_by": "研究または物理量でまとめ、各グループ内では出典順を維持する",
        "primary_warning": "値を解釈する前にお読みください",
        "graphene_warning": "出典が報告する ± の統計的な意味は未確認です。標準偏差（SD）、平均の標準誤差（SEM）、信頼区間、厳密な限界とは確定していません。",
        "mos2_warning": "出典の報告値には、印刷された q の未解決の不整合が残ります。実際のフィットに用いた q は不明で、再フィットや補正は行っていません。強度にもフィットした剛性と出典モデルの制約が引き継がれます。",
        "hbn_strength_warning": "出典の非線形有限要素解析（FEM）による強度は圧子直下の応力の体積平均であり、中心統計量の正確な名称と応力成分は未指定です。一様引張強度、局所最大値、補足図 S5 の最大 Von Mises 応力ではありません。",
        "hbn_stiffness_warning": "出典の剛性報告値は円形膜の力–たわみ関係のフィットから得られています。この推定は非線形 FEM による強度の算出とは異なります。",
        "sd_warning": "報告された標準偏差（SD）は平均の標準誤差（SEM）、信頼区間、68% の包含、厳密な限界、完全な不確かさ予算ではありません。平均化の方法、反復値の重み付け、包含範囲は不明です。",
    },
    "de": {
        "title": "Beobachtungen prüfen",
        "subtitle": "Nur zur Einsicht, in Quellenreihenfolge; kein Vergleich bei gleichen Bedingungen.",
        "policy": "Keine Rangfolge, Zusammenfassung von Werten oder Überlagerung. Steifigkeit und Festigkeit bleiben getrennte Größen; unbekannte Bedingungen belegen keine Gleichwertigkeit.",
        "translation_notice": "Die wissenschaftlichen Texte und Übersetzungen wurden maschinell unterstützt erstellt und noch nicht unabhängig fachlich oder muttersprachlich geprüft.",
        "snapshot_notice": "SHA-256-Prüfsummen identifizieren die beigefügten Katalogmetadaten, nicht die Bytes der Publikation. Quellen haben kein eigenes Versionsfeld.",
        "rights_notice": "Quellen-PDFs, Volltexte, Abbildungen, Screenshots und Rohmessdaten werden nicht weitergegeben. Lesezugang belegt keine Erlaubnis zur Nachnutzung; die Rechte des jeweiligen Dokuments gelten weiterhin.",
        "classification": "Quellenangabe · experimentell abgeleitet · modellabhängig · nur für den Katalog",
        "normalized": "Normalisierte Kataloganzeige",
        "normalized_notice": "Anzeige der exakt gespeicherten Katalogwerte in N/m; diese Anzeige ist kein wörtliches Quellenzitat.",
        "source_wording": "Originaler Wortlaut der Quelle",
        "source_wording_absent": "Für diesen Datensatz ist kein Quellenwortlaut zum Wert gespeichert; ein Zitat wird nicht rekonstruiert.",
        "original_context": "Der ursprüngliche Quellenkontext kann dreidimensionale Einheiten nennen; diese sind keine zusätzlichen ausgewählten Ergebnisse.",
        "identity": "Identität",
        "quantity": "Physikalische Größe",
        "study": "Studie",
        "record_version": "Datensatzversion",
        "uncertainty": "Bedeutung der Unsicherheit",
        "uncertainty_evidence": "Beleg zur Bedeutung der Unsicherheit",
        "statistic": "Statistik des zentralen Werts",
        "statistic_unknown": "Die genaue Bezeichnung der zentralen Statistik ist nicht angegeben; keinen Mittelwert annehmen.",
        "sample": "Probenangaben und Geltungsbereich der Zählungen",
        "conditions": "Bekannte und unbekannte Bedingungen",
        "model": "Ableitungsmodell der Quelle",
        "evidence": "Wertbeleg und Fundstelle",
        "verification": "Umfang der Einsicht und Prüfung",
        "rights": "Quellenrechte und Grenzen der Nachnutzung",
        "details": "Vollständige Quellen- und Datensatzdetails",
        "source_links": "Quellenlinks",
        "unknown": "Unbekannt / nicht belegt",
        "group_study": "Nach Studie gruppiert",
        "group_quantity": "Nach Größe gruppiert",
        "record": "Datensatz",
        "source": "Quelle",
        "catalog_schema": "Katalogschemaversion",
        "digest": "SHA-256 des Metadatenstands",
        "stiffness": "2D-Steifigkeit in der Ebene",
        "strength": "2D-Bruchfestigkeit",
        "no_comparison": "Zugehörige Zusammenfassungen einer Studie sind keine unabhängigen Bestätigungen. Diese Ansicht belegt weder Vergleichbarkeit noch theoretische Grenzen oder Bemessungswerte.",
        "command": "Experimentelle Katalogbeobachtungen ohne Berechnung oder Rangfolge prüfen",
        "inspect": "Beobachtungsansichten in Quellenreihenfolge exportieren",
        "output": "Ausgabeverzeichnis für JSON-, CSV-, SVG- und HTML-Prüfansichten",
        "ids": "Exakte Datensatz-IDs; Option für mehrere Datensätze wiederholen",
        "id": "Exakte Datensatz-ID; für mehrere Datensätze wiederholen",
        "source_filter": "Datensätze mit dieser exakten Quellen-ID auswählen",
        "source_id": "Filter auf eine exakte Quellen-ID",
        "quantity_filter": "Eine unterstützte zweidimensionale Größe auswählen",
        "group": "Navigation nach Studie oder Größe gruppieren; wissenschaftliche Interpretation bleibt unverändert",
        "group_by": "Nach Studie oder Größe gruppieren; Quellenreihenfolge innerhalb jeder Gruppe beibehalten",
        "primary_warning": "Vor der Interpretation des Werts lesen",
        "graphene_warning": "Die statistische Bedeutung des in der Quelle berichteten ± ist ungeprüft. Es ist nicht als Standardabweichung (SD), Standardfehler (SEM), Konfidenzintervall oder harte Grenze belegt.",
        "mos2_warning": "Die Quellenwerte behalten einen ungeklärten Widerspruch beim gedruckten q bei: Das tatsächlich beim Fit verwendete q ist unbekannt; es gab keinen neuen Fit und keine Korrektur. Auch die Festigkeit übernimmt den Vorbehalt zur angepassten Steifigkeit und zum Quellenmodell.",
        "hbn_strength_warning": "Die in der Quelle berichtete nichtlineare FEM-Festigkeit ist eine volumengemittelte Spannung unter dem Eindringkörper; die genaue zentrale Statistik und Spannungskomponente sind nicht angegeben. Sie ist keine gleichförmige Zugfestigkeit, kein lokales Maximum und nicht die maximale Von-Mises-Spannung aus Ergänzungsabbildung S5.",
        "hbn_stiffness_warning": "Die Steifigkeitsangabe der Quelle stammt aus einem Fit der Kraft-Durchbiegungs-Beziehung einer Kreismembran. Diese Ableitung unterscheidet sich von der nichtlinearen FEM-Auswertung der Festigkeit.",
        "sd_warning": "Die berichtete Standardabweichung (SD) ist kein Standardfehler (SEM), Konfidenzintervall, Beleg für 68% Abdeckung, harte Grenze oder vollständiges Unsicherheitsbudget. Mittelungsverfahren, Gewichtung der Wiederholungen und Abdeckung sind unbekannt.",
    },
}
