"""Authored, strict locales for the closed two-study descriptive presentation.

Canonical source prose, identifiers, bibliography and decimal strings remain
untranslated. Translation parity is not scientific or native-language review.
"""

SCOPE_KEYS = ('scope_comparison', 'scope_material', 'scope_unknowns',
              'scope_temperature', 'scope_sd', 'scope_limits')
FACT_IDS = ('preparation', 'printing', 'geometry', 'rate', 'statistic', 'sd',
            'temperature')

LABELS = {
    'en': {
        'compare_temperature_studies': 'Export the explicitly selected two-study descriptive temperature comparison',
        'profile_id': 'Exact reviewed two-study presentation profile ID (required)',
        'output': 'Output directory for comparison JSON, CSV, HTML and SVG files',
        'title': 'Two studies: reported tensile strength and temperature',
        'subtitle': 'Ten condition summaries from two different experiments. Read the protocol and statistic differences before the values.',
        'scope_heading': 'Interpretation limits',
        'scope_comparison': 'Descriptive juxtaposition only. Matched conditions and statistical independence are not established. Common units, PA12/15 wt.% declarations and ±45° labels do not make the formulations, protocols or central statistics equivalent.',
        'scope_material': 'These are different commercial formulations. Declared PA12 and 15 wt.% carbon fiber are not an independent composition assay. A 100% infill setting does not establish measured zero porosity. Drying does not establish measured specimen moisture.',
        'scope_unknowns': 'Actual moisture/RH, stress convention, stress-area basis and local strain rate remain unestablished. Source-cited standards are not verified compliance; nominal dimensions do not establish actual stress area. Unknown conditions are not treated as equal.',
        'scope_temperature': 'Temperature is a reported chamber condition, not a directly verified specimen reading; its uncertainty is unknown. 23 °C is not 25 °C. Even the shared 100 °C label does not establish matched conditioning. No rate ratio or merged condition row is inferred.',
        'scope_sd': 'SD is reported dispersion, not SEM, CI, uncertainty of a median, an observed endpoint range, coverage, a hard bound or a complete uncertainty budget. Raw replicates, their independence and the SD formula are unverified; counts do not justify calculating a CI.',
        'scope_limits': 'No interpolation, extrapolation, fit, pooling, normalization, deltas, ranking, significance, material prediction, design allowable or geometry-derived conversion. Agreement between transcriptions is not experimental replication or scientific validation.',
        'protocol_heading': 'Source-specific protocols, before any property values',
        'fact_preparation': 'Product and preparation',
        'fact_printing': 'Printing',
        'fact_geometry': 'Test and geometry',
        'fact_rate': 'Reported displacement rate',
        'fact_statistic': 'Central statistic and count',
        'fact_sd': 'SD evidence',
        'fact_temperature': 'Temperature conditions',
        'ciganas_preparation': 'Fiberlogy PA12 CF15; horizontal FFF, alternating +45°/−45°; drying 80 °C for 12 h; postprint annealing unreported.',
        'zach_preparation': 'Bambu Lab PAHT-CF; flat FFF, ±45°; predrying and selected annealing each 80 °C for 12 h. Natural-convection cooling to room temperature in a vacuum-sealed dehumidified container; cooling rate unknown. Preparation wording is ambiguous.',
        'ciganas_printing': 'Creality K1 MAX; 0.6 mm nozzle; 265 °C extrusion.',
        'zach_printing': 'Bambu Lab X1 Carbon; 0.4 mm nozzle; 290 °C extrusion.',
        'ciganas_geometry': 'Step-Lab UD08. Nominal dimensions: length 150 mm, thickness 3 mm, narrow/wide width 10/20 mm. Gauge 80 mm differs from the 110 mm grip/strain reference, which includes transition regions.',
        'zach_geometry': 'Instron 5967. Drawing annotations only; caption unit not established. Narrow width, actual stress area, gauge length and grip separation unknown; straight-section length is not assumed to be gauge length.',
        'ciganas_rate': '1 mm/min displacement/crosshead rate; not measured local strain rate.',
        'zach_rate': '10 mm/s reported displacement rate, as printed; control channel unknown. No silent correction to mm/min.',
        'ciganas_statistic': 'Central statistic and aggregation unnamed; three tensile tests per temperature condition.',
        'zach_statistic': 'Reported median; five specimens per orientation × temperature × annealing group.',
        'ciganas_sd': 'Table 3 UTS row prints MPa ± SD. The reported SD unit is MPa.',
        'zach_sd': 'Separate SD column has no printed unit. MPa is inferred from the UTS context; SD-to-Pa scaling is conditional on that inference.',
        'ciganas_temperature': 'Six reported chamber conditions; 30 min stabilization. Direct specimen temperature and temperature uncertainty unreported.',
        'zach_temperature': 'Four reported chamber conditions; 30 min conditioning. Direct specimen temperature and temperature uncertainty unestablished.',
        'ciganas_name': 'Ciganas et al. (2026)',
        'zach_name': 'Zach and Dudescu (2025)',
        'ciganas_product': 'Fiberlogy PA12 CF15 · horizontal FFF · annealing unreported',
        'zach_product': 'Bambu Lab PAHT-CF · flat FFF · annealed ±45° group',
        'ciganas_y_axis': 'Reported central UTS (MPa); statistic unspecified',
        'zach_y_axis': 'Reported median UTS (MPa)',
        'ciganas_count': 'n=3 tensile tests per temperature condition; independence unverified',
        'zach_count': 'n=5 specimens per orientation × temperature × annealing group; independence unverified',
        'ciganas_sd_notice': 'SD in MPa, explicit in the Table 3 UTS ± SD row',
        'zach_sd_notice': 'SD unit MPa inferred from UTS context; not printed in the SD header',
        'glyph_legend': 'Dots show reported central summaries only. Reported SD is listed separately below; no uncertainty endpoints are drawn. Missing temperature whiskers mean uncertainty was not reported, not zero.',
        'x_axis': 'Reported chamber condition (°C)',
        'axis_notice': 'Both panels use 15–155 °C and 0–65 MPa display axes. These are padding, not validated ranges or material limits. Tick marks are references, not observations; exact tested conditions are in each table.',
        'plot_description': 'Separate linear axes with equally styled, unconnected central-value dots. The following table gives exact source strings and separate reported SD; no calculated endpoints.',
        'ciganas_table_central': 'Central UTS (MPa); statistic unspecified',
        'zach_table_central': 'Median UTS (MPa)',
        'ciganas_table_sd': 'Reported SD (MPa)',
        'zach_table_sd': 'SD (MPa inferred from UTS context)',
        'temperature': 'Chamber (°C)',
        'table_heading': 'Exact values and separate reported SD',
        'table_notice': 'Source strings and trailing zeros are preserved. Printed digits do not establish resolution or accuracy. The two studies remain separate tables.',
        'source_heading': 'Sources, locators, revisions and rights',
        'locator': 'Selected source cells',
        'component': 'Table / expanded-table locator',
        'ciganas_locator': 'Table 3, row “Ultimate tensile strength, MPa ± SD”; temperature columns 23, 40, 60, 80, 100, 120 °C.',
        'zach_locator': 'Appendix A, Table A1; annealed ±45° rows; temperature blocks 25, 50, 100, 150 °C; “σUTS [MPa]” and “Standard Deviation” columns. Median: Section 3.1.',
        'revision': 'HTML inspected',
        'updated': 'reported HTML update',
        'pdf_notice': 'Publisher PDFs were not inspected; pagination and HTML/PDF equivalence are unestablished. Revision descriptors are not immutable source hashes.',
        'ciganas_discrepancy': 'A search-rendered snapshot and directly inspected current HTML disagree on two engine-load cells in unselected Table 4. The six selected Table 3 UTS/SD pairs agree across current HTML, visual checking and a second transcription.',
        'zach_discrepancy': 'Search-rendered discussion arrangement differed; no selected-cell discrepancy found. Section 2.2 describes annealing for all specimens, while Table A1/Section 2.3 distinguish groups: only explicitly annealed rows are selected. Possible prior-study non-annealed overlap was not audited; independence is not established.',
        'adaptation': 'CC BY 4.0 adaptation: selected factual strings preserved and reorganized into separate central-value plots and SD tables; curator notes added. This separately curated named descriptive presentation does not change scientific admission or review status. Exact SI re-expression remains metadata; Zach SD scaling is conditional. No source PDFs, figures, screenshots, HTML dumps, raw data or supplier assets are redistributed. MIT covers original project contributions only; no author or publisher endorsement is implied.',
        'review': 'Scientific wording, the new presentation and translations are machine-assisted and not independently scientifically or native-language reviewed. Transcription agreement verifies copying only.',
        'metadata_notice': 'Full source/record snapshots, original notation, nulls, evidence, exact SI metadata and catalog-metadata digests are retained in HTML audit details and JSON/CSV exports. Digests do not identify publisher artifact bytes.',
        'details': 'Complete validated bundle and audit metadata (inert text)',
    },
    'zh': {
        'compare_temperature_studies': '导出明确选定的两项研究描述性温度对照',
        'profile_id': '经审定的两研究展示配置精确 ID（必填）',
        'output': '对照 JSON、CSV、HTML 和 SVG 文件的输出目录',
        'title': '两项研究：报告的抗拉强度与温度',
        'subtitle': '来自两个不同实验的十组条件汇总值。请先阅读试验方案与统计量的差异，再解读数值。',
        'scope_heading': '解读限制',
        'scope_comparison': '仅作描述性并列展示。尚未确立匹配条件或统计独立性。共同单位、PA12/15 wt.% 声明和 ±45° 标签不能确立配方、方案或中心统计量等同。',
        'scope_material': '这是不同的商业配方。声明的 PA12 和 15 wt.% 碳纤维并非独立成分测定。100% 填充设置不确立实测零孔隙率；干燥处理不确立实测试样含水量。',
        'scope_unknowns': '实际含水量/相对湿度、应力约定、应力面积依据及局部应变率仍未确立。引用标准不等于经核实符合标准；标称尺寸不确立实际应力面积。未知条件不视为相等。',
        'scope_temperature': '温度是报告的试验箱条件，并非直接核实的试样温度；温度不确定度未知。23 °C 不等于 25 °C，即使同为 100 °C 也不确立调节条件匹配。不推导速率比，也不合并条件行。',
        'scope_sd': 'SD 是报告的离散程度，并非 SEM、置信区间、中位数不确定度、观测端点范围、覆盖率、硬界限或完整不确定度预算。原始重复数据、其独立性和 SD 公式未经核实；仅凭样本数不能据此计算置信区间。',
        'scope_limits': '不作插值、外推、拟合、合并、归一化、差值、排名、显著性、材料预测、设计许用值或由几何推导的换算。转录一致不构成实验复现或科学验证。',
        'protocol_heading': '来源专属试验方案：先于任何物性数值',
        'fact_preparation': '产品与制备',
        'fact_printing': '打印',
        'fact_geometry': '试验与几何尺寸',
        'fact_rate': '报告的位移速率',
        'fact_statistic': '中心统计量与数量',
        'fact_sd': 'SD 依据',
        'fact_temperature': '温度条件',
        'ciganas_preparation': 'Fiberlogy PA12 CF15；水平 FFF，交替 +45°/−45°；80 °C 干燥 12 h；打印后退火未报告。',
        'zach_preparation': 'Bambu Lab PAHT-CF；平放 FFF，±45°；预干燥与所选退火均为 80 °C、12 h。在真空密封除湿容器中自然对流冷却至室温；冷却速率未知。制备表述存在歧义。',
        'ciganas_printing': 'Creality K1 MAX；0.6 mm 喷嘴；265 °C 挤出。',
        'zach_printing': 'Bambu Lab X1 Carbon；0.4 mm 喷嘴；290 °C 挤出。',
        'ciganas_geometry': 'Step-Lab UD08。标称尺寸：长 150 mm、厚 3 mm、窄/宽段 10/20 mm。80 mm 标距不同于包含过渡区的 110 mm 夹距/应变参考长度。',
        'zach_geometry': 'Instron 5967。仅为图示标注；图注单位未确立。窄段宽度、实际应力面积、标距与夹距未知；不将直段长度认定为标距。',
        'ciganas_rate': '1 mm/min 位移/横梁速率；并非实测局部应变率。',
        'zach_rate': '原文报告 10 mm/s 位移速率；控制通道未知。不擅自改为 mm/min。',
        'ciganas_statistic': '中心统计量和汇总方式未命名；每个温度条件三次拉伸试验。',
        'zach_statistic': '报告的中位数；每个方向 × 温度 × 退火组五个试样。',
        'ciganas_sd': '表 3 UTS 行印有 MPa ± SD；报告 SD 的单位为 MPa。',
        'zach_sd': '独立 SD 列未印单位；由 UTS 上下文推断为 MPa。SD 转为 Pa 依赖这一推断。',
        'ciganas_temperature': '六个报告的试验箱条件；稳定 30 min。直接试样温度与温度不确定度未报告。',
        'zach_temperature': '四个报告的试验箱条件；调节 30 min。直接试样温度与温度不确定度未确立。',
        'ciganas_name': 'Ciganas 等（2026）',
        'zach_name': 'Zach 和 Dudescu（2025）',
        'ciganas_product': 'Fiberlogy PA12 CF15 · 水平 FFF · 退火未报告',
        'zach_product': 'Bambu Lab PAHT-CF · 平放 FFF · 退火 ±45° 组',
        'ciganas_y_axis': '报告的中心 UTS（MPa）；统计量未指明',
        'zach_y_axis': '报告的 UTS 中位数（MPa）',
        'ciganas_count': '每个温度条件 n=3 次拉伸试验；独立性未经核实',
        'zach_count': '每个方向 × 温度 × 退火组 n=5 个试样；独立性未经核实',
        'ciganas_sd_notice': 'SD 单位为 MPa，表 3 UTS ± SD 行明确给出',
        'zach_sd_notice': 'SD 的 MPa 单位由 UTS 上下文推断，并非 SD 表头印出的单位',
        'glyph_legend': '圆点仅表示报告的中心汇总值。报告的 SD 单列于下方，不绘制不确定度端点。未绘温度须线表示未报告不确定度，并非不确定度为零。',
        'x_axis': '报告的试验箱条件（°C）',
        'axis_notice': '两图均采用 15–155 °C 与 0–65 MPa 显示轴。这些范围是显示留白，并非有效范围或材料极限。刻度是参考，并非观测；各表列出精确试验条件。',
        'plot_description': '独立线性坐标轴，样式相同且互不连接的中心值圆点。下表列出精确来源字符串及单列的报告 SD；没有计算端点。',
        'ciganas_table_central': '中心 UTS（MPa）；统计量未指明',
        'zach_table_central': 'UTS 中位数（MPa）',
        'ciganas_table_sd': '报告 SD（MPa）',
        'zach_table_sd': 'SD（由 UTS 上下文推断为 MPa）',
        'temperature': '试验箱（°C）',
        'table_heading': '精确数值与单列报告 SD',
        'table_notice': '保留来源字符串及末尾零。印出位数不确立分辨率或准确度。两项研究分别列为独立表格。',
        'source_heading': '来源、位置、修订与权利',
        'locator': '选定来源单元格',
        'component': '表格 / 展开表格位置',
        'ciganas_locator': 'Table 3，“Ultimate tensile strength, MPa ± SD” 行；温度列 23、40、60、80、100、120 °C。',
        'zach_locator': 'Appendix A，Table A1；annealed ±45° 行；温度组 25、50、100、150 °C；“σUTS [MPa]” 与 “Standard Deviation” 列。中位数依据：Section 3.1。',
        'revision': 'HTML 查阅日期',
        'updated': '报告的 HTML 更新',
        'pdf_notice': '未查阅出版商 PDF；页码和 HTML/PDF 等同性未确立。修订描述并非不可变来源哈希。',
        'ciganas_discrepancy': '搜索呈现快照与直接查阅的当前 HTML 的差异涉及未选入 Table 4 的两个发动机负载单元格。所选 Table 3 六组 UTS/SD 在当前 HTML、目视核查及第二次转录间一致。',
        'zach_discrepancy': '搜索呈现的讨论排列不同，未发现所选单元格差异。Section 2.2 称全部试样退火，而 Table A1/Section 2.3 区分组别；仅选择明确退火行。与早期研究未退火数据可能重叠，尚未审计；独立性未确立。',
        'adaptation': 'CC BY 4.0 改编：保留所选事实字符串，重组为独立中心值图和 SD 表，并加入整理说明。本单独整理的命名描述性展示不改变科学准入或审查状态。精确 SI 重表达仅作元数据；Zach 的 SD 换算有条件。不再分发来源 PDF、图、截图、HTML 转储、原始数据或供应商素材。MIT 仅涵盖原创项目贡献；不暗示作者或出版商认可。',
        'review': '科学表述、新展示及译文由机器辅助，尚未经独立科学审查或母语审校。转录一致仅核实抄录。',
        'metadata_notice': '完整来源/记录快照、原始记法、null、证据、精确 SI 元数据及目录元数据摘要保留于 HTML 审计详情和 JSON/CSV 导出中。摘要不标识出版商文件字节。',
        'details': '完整校验数据包与审计元数据（静态文本）',
    },
    'ja': {
        'compare_temperature_studies': '明示的に選択した二研究の記述的な温度比較を出力',
        'profile_id': '審定された二研究表示プロファイルの正確な ID（必須）',
        'output': '比較 JSON、CSV、HTML、SVG ファイルの出力先',
        'title': '二つの研究：報告された引張強さと温度',
        'subtitle': '異なる二つの実験からの十の条件要約値。値の前に試験手順と統計量の違いを確認してください。',
        'scope_heading': '解釈上の限界',
        'scope_comparison': '記述的な並列表示のみです。条件の一致や統計的独立性は確立していません。同じ単位、PA12/15 wt.% の表示、±45° の表記は、配合、手順、中心統計量の同等性を意味しません。',
        'scope_material': '異なる市販配合です。PA12 と炭素繊維 15 wt.% の表示は独立した組成分析ではありません。100% 充填設定は実測空隙率ゼロを確立せず、乾燥処理は試験片の実測含水量を確立しません。',
        'scope_unknowns': '実際の含水量/相対湿度、応力の規約、応力面積の基準、局所ひずみ速度は未確立です。規格の引用は適合確認ではなく、公称寸法は実際の応力面積を確立しません。不明条件を同一と扱いません。',
        'scope_temperature': '温度は報告された試験槽条件であり、直接確認した試験片温度ではありません。温度の不確かさは不明です。23 °C と 25 °C は異なり、同じ 100 °C でも調整条件の一致は確立しません。速度比や条件行の統合は行いません。',
        'scope_sd': 'SD は報告されたばらつきであり、SEM、信頼区間、中央値の不確かさ、観測端点範囲、包含率、厳密な限界、完全な不確かさ予算ではありません。反復生データ、独立性、SD 式は未確認で、試験数のみでは信頼区間を計算できません。',
        'scope_limits': '補間、外挿、フィット、統合、正規化、差分、順位付け、有意性、材料予測、設計許容値、形状由来の換算は行いません。転記の一致は実験再現や科学的検証ではありません。',
        'protocol_heading': '物性値に先立つ出典別の試験手順',
        'fact_preparation': '製品と作製',
        'fact_printing': '造形',
        'fact_geometry': '試験と形状',
        'fact_rate': '報告変位速度',
        'fact_statistic': '中心統計量と試験数',
        'fact_sd': 'SD の根拠',
        'fact_temperature': '温度条件',
        'ciganas_preparation': 'Fiberlogy PA12 CF15；水平 FFF、交互 +45°/−45°；80 °C で 12 h 乾燥；造形後のアニーリングは未報告。',
        'zach_preparation': 'Bambu Lab PAHT-CF；平置き FFF、±45°；予備乾燥と選択群のアニーリングは各 80 °C、12 h。真空密封された除湿容器内で自然対流により室温まで冷却；冷却速度は不明。作製の記述に曖昧さがあります。',
        'ciganas_printing': 'Creality K1 MAX；ノズル 0.6 mm；押出温度 265 °C。',
        'zach_printing': 'Bambu Lab X1 Carbon；ノズル 0.4 mm；押出温度 290 °C。',
        'ciganas_geometry': 'Step-Lab UD08。公称寸法：長さ 150 mm、厚さ 3 mm、狭幅/広幅 10/20 mm。標点距離 80 mm は遷移部を含むつかみ間隔/ひずみ基準長 110 mm と異なります。',
        'zach_geometry': 'Instron 5967。図面注記のみで、キャプションの単位は未確立。狭幅、実際の応力面積、標点距離、つかみ間隔は不明；直線部長さを標点距離とはみなしません。',
        'ciganas_rate': '変位/クロスヘッド速度 1 mm/min；実測局所ひずみ速度ではありません。',
        'zach_rate': '記載どおりの変位速度 10 mm/s；制御チャンネルは不明。mm/min に黙って修正しません。',
        'ciganas_statistic': '中心統計量と集約法は未命名；温度条件ごとに三回の引張試験。',
        'zach_statistic': '報告された中央値；方向 × 温度 × アニーリング群ごとに五本の試験片。',
        'ciganas_sd': 'Table 3 の UTS 行に MPa ± SD と明記。報告 SD の単位は MPa。',
        'zach_sd': '独立した SD 列に単位の印刷はありません。UTS の文脈から MPa と推定；SD の Pa 換算はこの推定を条件とします。',
        'ciganas_temperature': '六つの報告試験槽条件；30 min 安定化。直接測定した試験片温度と温度の不確かさは未報告。',
        'zach_temperature': '四つの報告試験槽条件；30 min 調整。直接測定した試験片温度と温度の不確かさは未確立。',
        'ciganas_name': 'Ciganas ほか（2026）',
        'zach_name': 'Zach・Dudescu（2025）',
        'ciganas_product': 'Fiberlogy PA12 CF15 · 水平 FFF · アニーリング未報告',
        'zach_product': 'Bambu Lab PAHT-CF · 平置き FFF · アニーリング ±45° 群',
        'ciganas_y_axis': '報告中心 UTS（MPa）；統計量は未指定',
        'zach_y_axis': '報告 UTS 中央値（MPa）',
        'ciganas_count': '各温度条件 n=3 回の引張試験；独立性は未確認',
        'zach_count': '各方向 × 温度 × アニーリング群 n=5 本；独立性は未確認',
        'ciganas_sd_notice': 'SD は MPa、Table 3 の UTS ± SD 行に明記',
        'zach_sd_notice': 'SD の MPa は UTS の文脈からの推定であり、SD 見出しの印刷単位ではありません',
        'glyph_legend': '点は報告された中心要約値のみです。報告 SD は下に別記し、不確かさの端点は描きません。温度のひげがないことは不確かさ未報告を意味し、ゼロを意味しません。',
        'x_axis': '報告された試験槽条件（°C）',
        'axis_notice': '両パネルの表示軸は 15–155 °C、0–65 MPa です。表示余白であり、検証済み範囲や材料限界ではありません。目盛りは参照であって観測ではなく、正確な試験条件は各表に記載します。',
        'plot_description': '独立した線形軸上に同一様式の接続されない中心値の点。後続の表に正確な出典文字列と別記の報告 SD を示します。計算された端点はありません。',
        'ciganas_table_central': '中心 UTS（MPa）；統計量未指定',
        'zach_table_central': 'UTS 中央値（MPa）',
        'ciganas_table_sd': '報告 SD（MPa）',
        'zach_table_sd': 'SD（UTS 文脈から MPa と推定）',
        'temperature': '試験槽（°C）',
        'table_heading': '正確な値と別記の報告 SD',
        'table_notice': '出典文字列と末尾のゼロを保持します。印刷桁数は分解能や正確さを確立しません。研究ごとに別の表を使用します。',
        'source_heading': '出典、位置、改訂と権利',
        'locator': '選択した出典セル',
        'component': '表 / 展開表の位置',
        'ciganas_locator': 'Table 3、“Ultimate tensile strength, MPa ± SD” 行；温度列 23、40、60、80、100、120 °C。',
        'zach_locator': 'Appendix A、Table A1；annealed ±45° 行；温度群 25、50、100、150 °C；“σUTS [MPa]” と “Standard Deviation” 列。中央値の根拠：Section 3.1。',
        'revision': 'HTML 確認日',
        'updated': '報告 HTML 更新',
        'pdf_notice': '出版社 PDF は未確認で、ページ番号と HTML/PDF の同等性は未確立です。改訂記述は不変の出典ハッシュではありません。',
        'ciganas_discrepancy': '検索表示スナップショットと直接確認した現行 HTML の相違は未選択 Table 4 の二つのエンジン負荷セルです。選択した Table 3 の六組の UTS/SD は現行 HTML、目視確認、第二の転記で一致しました。',
        'zach_discrepancy': '検索表示の考察配置に違いがありますが、選択セルの相違は見つかりませんでした。Section 2.2 は全試験片のアニーリングを記す一方、Table A1/Section 2.3 は群を区別するため、明示的なアニーリング行のみ選択します。先行研究の未処理データとの重複可能性は未監査で、独立性は未確立です。',
        'adaptation': 'CC BY 4.0 の改変：選択した事実文字列を保持し、別々の中心値図と SD 表に再構成し、整理者の注記を追加しました。この別途整理した記述的表示は科学的採用や審査状態を変更しません。正確な SI 再表現はメタデータのみで、Zach の SD 換算は条件付きです。出典 PDF、図、スクリーンショット、HTML ダンプ、生データ、供給者素材は再配布しません。MIT は独自のプロジェクト貢献のみを対象とし、著者・出版社の推奨を示しません。',
        'review': '科学的表現、新しい表示、翻訳は機械支援で作成され、独立した科学的審査や母語話者の審査を受けていません。転記一致が確認するのは書き写しのみです。',
        'metadata_notice': '完全な出典/記録スナップショット、原記法、null、証拠、正確な SI メタデータ、カタログメタデータのダイジェストは HTML 監査詳細と JSON/CSV 出力に保持します。ダイジェストは出版社成果物のバイトを特定しません。',
        'details': '完全な検証済みバンドルと監査メタデータ（静的テキスト）',
    },
    'de': {
        'compare_temperature_studies': 'Den ausdrücklich gewählten beschreibenden Temperaturvergleich zweier Studien exportieren',
        'profile_id': 'Exakte ID des geprüften Darstellungsprofils für zwei Studien (erforderlich)',
        'output': 'Ausgabeordner für Vergleichsdateien in JSON, CSV, HTML und SVG',
        'title': 'Zwei Studien: berichtete Zugfestigkeit und Temperatur',
        'subtitle': 'Zehn Bedingungszusammenfassungen aus zwei verschiedenen Experimenten. Versuchsabläufe und Statistik vor den Werten lesen.',
        'scope_heading': 'Grenzen der Interpretation',
        'scope_comparison': 'Nur beschreibende Gegenüberstellung. Übereinstimmende Bedingungen und statistische Unabhängigkeit sind nicht belegt. Gemeinsame Einheiten, PA12-/15-Gew.-%-Angaben und ±45°-Bezeichnungen begründen keine Gleichwertigkeit von Rezepturen, Abläufen oder zentralen Statistiken.',
        'scope_material': 'Es sind verschiedene kommerzielle Rezepturen. Die Angaben PA12 und 15 Gew.-% Kohlenstofffaser sind keine unabhängige Zusammensetzungsanalyse. 100% Füllgrad als Druckeinstellung belegt keine gemessene Porosität von null. Trocknung belegt keine gemessene Probenfeuchte.',
        'scope_unknowns': 'Tatsächliche Feuchte/relative Luftfeuchte, Spannungskonvention, Bezugsquerschnitt und lokale Dehnrate bleiben ungeklärt. Zitierte Normen sind kein geprüfter Konformitätsnachweis; Nennmaße belegen keinen tatsächlichen Spannungsquerschnitt. Unbekannte Bedingungen gelten nicht als gleich.',
        'scope_temperature': 'Temperatur ist eine berichtete Kammerbedingung, keine direkt bestätigte Probentemperatur; ihre Unsicherheit ist unbekannt. 23 °C ist nicht 25 °C. Auch die gemeinsame Angabe 100 °C belegt keine gleiche Konditionierung. Kein Ratenverhältnis und keine Zusammenführung von Bedingungszeilen.',
        'scope_sd': 'SD bezeichnet berichtete Streuung, nicht SEM, Konfidenzintervall, Unsicherheit des Medians, beobachteten Endpunktbereich, Überdeckung, harte Grenze oder vollständiges Unsicherheitsbudget. Rohwiederholungen, Unabhängigkeit und SD-Formel sind ungeprüft; die Anzahl rechtfertigt keine Berechnung eines Konfidenzintervalls.',
        'scope_limits': 'Keine Interpolation, Extrapolation, Anpassung, Bündelung, Normierung, Differenzen, Rangfolge, Signifikanz, Materialprognose, Auslegungskennwerte oder geometriegestützte Umrechnung. Übereinstimmende Übertragungen sind keine experimentelle Replikation oder wissenschaftliche Validierung.',
        'protocol_heading': 'Quellenspezifische Abläufe vor allen Materialkennwerten',
        'fact_preparation': 'Produkt und Vorbereitung',
        'fact_printing': 'Druck',
        'fact_geometry': 'Versuch und Geometrie',
        'fact_rate': 'Berichtete Verschiebungsrate',
        'fact_statistic': 'Zentrale Statistik und Anzahl',
        'fact_sd': 'SD-Beleg',
        'fact_temperature': 'Temperaturbedingungen',
        'ciganas_preparation': 'Fiberlogy PA12 CF15; horizontales FFF, wechselnd +45°/−45°; Trocknung 80 °C für 12 h; Tempern nach dem Druck nicht berichtet.',
        'zach_preparation': 'Bambu Lab PAHT-CF; flaches FFF, ±45°; Vortrocknung und ausgewähltes Tempern jeweils 80 °C für 12 h. Naturkonvektive Abkühlung auf Raumtemperatur in einem vakuumversiegelten entfeuchteten Behälter; Abkühlrate unbekannt. Mehrdeutige Vorbereitungsbeschreibung.',
        'ciganas_printing': 'Creality K1 MAX; 0.6-mm-Düse; 265 °C Extrusion.',
        'zach_printing': 'Bambu Lab X1 Carbon; 0.4-mm-Düse; 290 °C Extrusion.',
        'ciganas_geometry': 'Step-Lab UD08. Nennmaße: Länge 150 mm, Dicke 3 mm, schmale/breite Zone 10/20 mm. Messlänge 80 mm unterscheidet sich von der 110-mm-Einspann-/Dehnungsreferenz einschließlich Übergangszonen.',
        'zach_geometry': 'Instron 5967. Nur Zeichnungsangaben; Einheit in der Bildunterschrift nicht belegt. Schmale Breite, tatsächlicher Spannungsquerschnitt, Messlänge und Einspannabstand unbekannt; gerade Länge wird nicht als Messlänge übernommen.',
        'ciganas_rate': '1 mm/min Verschiebungs-/Traversenrate; keine gemessene lokale Dehnrate.',
        'zach_rate': '10 mm/s berichtete Verschiebungsrate, wie gedruckt; Regelkanal unbekannt. Keine stillschweigende Korrektur zu mm/min.',
        'ciganas_statistic': 'Zentrale Statistik und Aggregation unbenannt; drei Zugversuche je Temperaturbedingung.',
        'zach_statistic': 'Berichteter Median; fünf Proben je Orientierung × Temperatur × Tempergruppe.',
        'ciganas_sd': 'UTS-Zeile in Table 3 druckt MPa ± SD. Die berichtete SD-Einheit ist MPa.',
        'zach_sd': 'Separate SD-Spalte ohne gedruckte Einheit. MPa wird aus dem UTS-Kontext abgeleitet; SD-Umrechnung in Pa ist an diese Annahme gebunden.',
        'ciganas_temperature': 'Sechs berichtete Kammerbedingungen; 30 min Stabilisierung. Direkte Probentemperatur und Temperaturunsicherheit nicht berichtet.',
        'zach_temperature': 'Vier berichtete Kammerbedingungen; 30 min Konditionierung. Direkte Probentemperatur und Temperaturunsicherheit nicht belegt.',
        'ciganas_name': 'Ciganas et al. (2026)',
        'zach_name': 'Zach und Dudescu (2025)',
        'ciganas_product': 'Fiberlogy PA12 CF15 · horizontales FFF · Tempern unberichtet',
        'zach_product': 'Bambu Lab PAHT-CF · flaches FFF · getemperte ±45°-Gruppe',
        'ciganas_y_axis': 'Berichteter zentraler UTS-Wert (MPa); Statistik unbestimmt',
        'zach_y_axis': 'Berichteter UTS-Median (MPa)',
        'ciganas_count': 'n=3 Zugversuche je Temperaturbedingung; Unabhängigkeit ungeprüft',
        'zach_count': 'n=5 Proben je Orientierung × Temperatur × Tempergruppe; Unabhängigkeit ungeprüft',
        'ciganas_sd_notice': 'SD in MPa, ausdrücklich in der UTS-±-SD-Zeile von Table 3',
        'zach_sd_notice': 'SD-Einheit MPa aus UTS-Kontext abgeleitet; nicht im SD-Kopf gedruckt',
        'glyph_legend': 'Punkte zeigen nur berichtete zentrale Zusammenfassungen. Berichtete SD steht separat darunter; keine Unsicherheitsendpunkte werden gezeichnet. Fehlende Temperaturfehlerbalken bedeuten nicht berichtete Unsicherheit, nicht null.',
        'x_axis': 'Berichtete Kammerbedingung (°C)',
        'axis_notice': 'Beide Diagramme verwenden 15–155 °C und 0–65 MPa als Darstellungsachsen. Dies sind Ränder, keine validierten Bereiche oder Materialgrenzen. Teilstriche sind Referenzen, keine Beobachtungen; genaue Prüfbedingungen stehen in jeder Tabelle.',
        'plot_description': 'Separate lineare Achsen mit gleich gestalteten, unverbundenen Punkten der zentralen Werte. Die folgende Tabelle enthält exakte Quellzeichenfolgen und separat berichtete SD; keine berechneten Endpunkte.',
        'ciganas_table_central': 'Zentraler UTS-Wert (MPa); Statistik unbestimmt',
        'zach_table_central': 'UTS-Median (MPa)',
        'ciganas_table_sd': 'Berichtete SD (MPa)',
        'zach_table_sd': 'SD (MPa aus UTS-Kontext abgeleitet)',
        'temperature': 'Kammer (°C)',
        'table_heading': 'Exakte Werte und separate berichtete SD',
        'table_notice': 'Quellzeichenfolgen und Endnullen bleiben erhalten. Gedruckte Stellen belegen keine Auflösung oder Genauigkeit. Beide Studien behalten separate Tabellen.',
        'source_heading': 'Quellen, Fundstellen, Revisionen und Rechte',
        'locator': 'Ausgewählte Quellzellen',
        'component': 'Tabellen-/erweiterte Tabellenfundstelle',
        'ciganas_locator': 'Table 3, Zeile „Ultimate tensile strength, MPa ± SD“; Temperaturspalten 23, 40, 60, 80, 100, 120 °C.',
        'zach_locator': 'Appendix A, Table A1; annealed-±45°-Zeilen; Temperaturblöcke 25, 50, 100, 150 °C; Spalten „σUTS [MPa]“ und „Standard Deviation“. Median: Section 3.1.',
        'revision': 'HTML eingesehen',
        'updated': 'berichtete HTML-Aktualisierung',
        'pdf_notice': 'Verlags-PDFs wurden nicht eingesehen; Paginierung und HTML/PDF-Gleichwertigkeit sind ungeklärt. Revisionsbeschreibungen sind keine unveränderlichen Quellen-Hashes.',
        'ciganas_discrepancy': 'Die Abweichung zwischen Suchdarstellungs-Snapshot und direkt eingesehenem aktuellem HTML betrifft zwei Motorlastzellen der nicht ausgewählten Table 4. Die sechs gewählten UTS/SD-Paare aus Table 3 stimmen in aktuellem HTML, Sichtprüfung und zweiter Übertragung überein.',
        'zach_discrepancy': 'Die Suchdarstellung ordnete Diskussionstext anders an; keine Abweichung in ausgewählten Zellen gefunden. Section 2.2 beschreibt Tempern aller Proben, während Table A1/Section 2.3 Gruppen unterscheiden: Nur ausdrücklich getemperte Zeilen sind ausgewählt. Mögliche Überlappung ungetemperter Daten mit einer früheren Studie wurde nicht geprüft; Unabhängigkeit ist unbelegt.',
        'adaptation': 'CC BY 4.0, Bearbeitung: Ausgewählte Faktenzeichenfolgen bleiben erhalten und werden in separate Zentralwertdiagramme und SD-Tabellen umgeordnet; Kuratorenhinweise ergänzt. Diese separat kuratierte benannte Darstellung ändert weder wissenschaftliche Zulassung noch Prüfstatus. Exakte SI-Umrechnung bleibt Metadatum; Zach-SD-Umrechnung ist bedingt. Keine Weitergabe von Quellen-PDFs, Abbildungen, Screenshots, HTML-Abzügen, Rohdaten oder Lieferantenmaterial. MIT gilt nur für eigene Projektbeiträge; keine Billigung durch Autoren oder Verlag wird behauptet.',
        'review': 'Wissenschaftliche Formulierungen, neue Darstellung und Übersetzungen sind maschinengestützt und weder unabhängig wissenschaftlich noch muttersprachlich geprüft. Übereinstimmende Übertragung bestätigt nur das Abschreiben.',
        'metadata_notice': 'Vollständige Quellen-/Datensatz-Snapshots, Originalnotation, null-Werte, Belege, exakte SI-Metadaten und Katalog-Metadaten-Digests bleiben in HTML-Prüfdetails und JSON/CSV erhalten. Digests identifizieren keine Bytes von Verlagsartefakten.',
        'details': 'Vollständiges validiertes Paket und Prüfmetadaten (inaktiver Text)',
    },
}


def labels(lang='en'):
    """Return independent authored labels, with no English fallback."""
    from .observation_study_comparison import _require
    _require(type(lang) is str and lang in LABELS,
             'unsupported observation-study-comparison language')
    return dict(LABELS[lang])
