"""Parallel authored labels for the closed source-temperature display.

Source strings, identifiers and bibliographic text are never translated.
All four versions remain machine-assisted and not independently reviewed.
"""

LABELS = {
    'en': {
        'table_column': 'Table 3 · temperature column',
        'table_row': 'Shared Table 3 row',
        'table_container': 'Table container',
        'expanded_table': 'Expanded-table locator',
        'record_cell': 'Record / source cell',
        'audit_details': 'Full protocol, provenance, SI and snapshot audit details',
        'metadata_exports': 'Complete source/record snapshots, nulls, exact SI values and metadata digests remain in the JSON/CSV exports and HTML audit details.',
        'uncertainty_definition': 'Shared uncertainty definition; condition-specific SD magnitudes are in the exact source table',
        'plot_temperature': 'Export the six approved source-temperature summaries with reported SD whiskers',
        'dataset_id': 'Exact approved temperature-observation dataset ID (required)',
        'output': 'Output directory for temperature-plot JSON, CSV, SVG and HTML files',
        'title': 'PA12 CF15: reported tensile strength at test temperatures',
        'subtitle': 'Six discrete source summaries · one source-reported protocol · catalog only',
        'scope_heading': 'Read before interpreting the plot or values',
        'scope_protocol': 'Six condition summaries from one study of horizontally FFF-printed Fiberlogy PA12 CF15 with alternating +45°/−45° raster. Same source-reported protocol only; no cross-study or universal material claim. Shared metadata do not prove identical conditioning or material invariance.',
        'scope_temperature': 'X is the reported chamber test condition after 30 minutes of stabilization. Actual specimen temperature and temperature uncertainty are unreported. No x whiskers does not mean zero uncertainty; dot width does not show temperature precision.',
        'scope_statistic': 'Dots are reported central UTS values. The central statistic, aggregation, stress convention and stress-area basis are unknown; the centers are not identified as means.',
        'scope_sd': 'Vertical whiskers reproduce ± reported standard deviation (SD). Three tensile tests per condition are reported; raw replicates and their independence are unverified. The SD formula is unknown. SD is not SEM, a confidence interval, an observed min–max range, a hard bound, a coverage statement or a complete uncertainty budget.',
        'scope_preparation': 'Specific preparation, geometry and the 1 mm/min crosshead-rate protocol apply. Drying at 80 °C for 12 h does not establish measured moisture; humidity/moisture are unknown. Declared 15 wt.% fibers and 100% infill do not establish measured composition or zero porosity.',
        'scope_limits': 'No interpolation, extrapolation, fitting, material prediction, ranking, design allowable or safety claim. Transcription/software checks are not independent scientific validation. These summaries are not six independent confirmations.',
        'glyph_legend': 'Dot: reported central value. Vertical capped whisker: central value ± source-reported SD; n=3 tensile tests per condition. SD is not a confidence interval or a bound. Temperature uncertainty is unreported.',
        'x_axis': 'Reported chamber test condition (°C)',
        'y_axis': 'Source-reported UTS (MPa)',
        'plot_description': 'Six unconnected, equally sized dots at the six reported chamber conditions, with vertical capped whiskers for reported SD. Exact source values and condition-scoped counts are in the following table.',
        'axis_notice': 'Reported conditions: only the six labeled points, 23–120 °C. Display margins 15–125 °C add no observations or validated range. Y display 0–55 MPa: zero is a visual baseline, not an experimental bound. Whisker endpoints are central ± SD rendering arithmetic, not additional observations.',
        'table_heading': 'Exact source cells',
        'table_notice': 'Table 3 source strings retain their trailing zeros. Printed digits do not establish resolution or accuracy. Record IDs and source-cell locators identify every row.',
        'temperature': 'Chamber label (°C)',
        'source_value': 'Exact source cell (MPa)',
        'reported_sd': 'Reported SD (MPa)',
        'sample_count': 'Tensile tests per condition (n)',
        'sd_type': 'Reported standard deviation (SD)',
        'record': 'Record',
        'source_cell': 'Source-cell locator',
        'protocol_heading': 'Preparation, geometry and protocol',
        'protocol_geometry': 'Source-reported nominal dog-bone geometry: length 150 mm; gauge length 80 mm; thickness 3 mm; narrow/wide widths 10/20 mm; grip separation 110 mm. Crosshead-derived engineering strain uses the full 110 mm, including transition regions, not only the 80 mm gauge. Local strain rate, dimensional tolerances and measured stress cross-section are unknown. No stress is reconstructed from geometry.',
        'protocol_preparation': 'Creality K1 MAX FFF; horizontal build; alternating +45°/−45° raster; 100% linear infill; five contours; 0.2 mm layers; 0.6 mm nozzle; nozzle/bed 265/100 °C; inner/outer wall speeds 60/60 mm/s; reported cooling 100%; reported specimen mass 6.42 g. Step-Lab UD08 tension with integrated thermal chamber. Filament diameter 1.75 mm; supplied spool mass 0.5 kg.',
        'protocol_unknowns': 'Atmosphere and pressure are unknown. Numerical relative humidity, specimen moisture, temperature sensor location, stability tolerance, and tensile heating rate are unknown. No DMA heating rate is transferred. Engineering-strain wording does not establish engineering stress. ISO 527 is cited; compliance and the article-reported standard URL were not independently verified.',
        'shared_metadata': 'Complete shared protocol and condition metadata (canonical keys; null remains unknown)',
        'identity': 'Dataset and admitted shared-protocol group',
        'source_heading': 'Source, version and rights',
        'revision': 'Publisher HTML inspected 3 October 2026, reported update 3 September 2026 02:53 CEST. PDF not inspected; no PDF-equivalence claim. The cached/live discrepancy is in unselected Table 4. Only the six selected Table 3 UTS/SD cells agree across current HTML, visual inspection and a second transcription; this is not experimental reproduction.',
        'adaptation': 'CC BY 4.0 adaptation: source numbers and SD strings preserved, reorganized and plotted as discrete condition summaries; SI units re-expressed; curator notes are original. Publisher endorsement is not implied. Manufacturer Table 1 and source PDFs, figures, screenshots, HTML dumps and raw measurements are excluded. MIT covers original project contributions and does not replace source rights.',
        'si_heading': 'Separate exact SI re-expression',
        'si_notice': '1 MPa = 1000000 Pa exactly. These are the same observations, not additional plotted records. Unit scaling adds no measurement precision and uses no geometry or thickness.',
        'metadata_heading': 'Provenance and metadata integrity',
        'snapshot_notice': 'SHA-256 values identify bundled catalog metadata, not original publisher artifact bytes. Full scientific snapshots and nulls are retained in the JSON export.',
        'evidence': 'Evidence and component locator',
        'source': 'Source',
        'rights': 'Rights and attribution',
        'details': 'Complete validated plot bundle',
        'translation_notice': 'Scientific wording and translations are machine-assisted and have not been independently scientifically or native-language reviewed.',
    },
    'zh': {
        'table_column': '表 3 · 温度列',
        'table_row': '表 3 共同数据行',
        'table_container': '表格容器',
        'expanded_table': '展开表格位置',
        'record_cell': '记录 / 来源单元格',
        'audit_details': '完整试验方案、来源链、SI 与快照审计详情',
        'metadata_exports': '完整来源与记录快照、null、精确 SI 数值和元数据摘要均保留在 JSON/CSV 导出及 HTML 审计详情中。',
        'uncertainty_definition': '共同不确定度定义；各条件 SD 数值见精确来源表',
        'plot_temperature': '导出六组获准的来源温度汇总值及报告的标准差须线',
        'dataset_id': '获准温度观测数据集的精确 ID（必填）',
        'output': '温度图 JSON、CSV、SVG 和 HTML 文件的输出目录',
        'title': 'PA12 CF15：报告试验温度下的抗拉强度',
        'subtitle': '六组离散来源汇总值 · 同一来源报告的试验方案 · 仅用于目录',
        'scope_heading': '解读图和数值前请先阅读',
        'scope_protocol': '这六组条件汇总值来自同一项研究：水平 FFF 打印的 Fiberlogy PA12 CF15，采用交替 +45°/−45° 栅格。仅限同一来源报告的试验方案；不主张跨研究或普适材料结论。共同元数据不能证明实际调湿条件相同或材料不变。',
        'scope_temperature': 'X 是稳定 30 分钟后报告的试验箱温度条件。实际试样温度和温度不确定度未报告。没有 x 方向须线并不表示不确定度为零；圆点宽度也不表示温度精度。',
        'scope_statistic': '圆点表示报告的 UTS 中心值。中心统计量、汇总方式、应力约定和应力计算面积依据未知；不能将中心值认定为均值。',
        'scope_sd': '竖直须线重现 ± 报告的标准差（SD）。来源报告每个条件进行了三次拉伸试验；原始重复试验数据及其独立性未经核实。SD 公式未知。SD 并非均值标准误（SEM）、置信区间、观测最小–最大范围、硬界限、覆盖率声明或完整不确定度预算。',
        'scope_preparation': '仅适用于所述制备、几何尺寸和 1 mm/min 横梁速度方案。在 80 °C 下干燥 12 h 不确立实测含水量；湿度与含水量未知。标称 15 wt.% 纤维和 100% 填充不确立实测成分或零孔隙率。',
        'scope_limits': '不作插值、外推、拟合、材料预测、排名、工程许用值或安全声明。转录和软件核查不构成独立科学验证。这些汇总值并非六次独立验证。',
        'glyph_legend': '圆点：报告的中心值。带端帽竖直须线：中心值 ± 来源报告的 SD；每个条件 n=3 次拉伸试验。SD 不是置信区间或界限。温度不确定度未报告。',
        'x_axis': '报告的试验箱温度条件（°C）',
        'y_axis': '原文报告的极限抗拉强度 UTS（MPa）',
        'plot_description': '六个报告的试验箱条件各对应一个大小相同、互不连接的圆点，带表示报告 SD 的端帽竖直须线。精确来源数值和每条件试验次数见下表。',
        'axis_notice': '报告的条件仅为六个标记点，跨度 23–120 °C。15–125 °C 显示留白不增加观测或有效范围。Y 显示范围为 0–55 MPa；零仅为视觉基线，并非实验界限。须线端点仅由中心值 ± SD 的绘图运算得到，并非新增观测。',
        'table_heading': '精确来源单元格',
        'table_notice': '表 3 原始数值字符串保留末尾零。印出位数不确立分辨率或准确度。记录 ID 和来源单元格位置标识每一行。',
        'temperature': '试验箱标签（°C）',
        'source_value': '精确来源单元格（MPa）',
        'reported_sd': '报告的 SD（MPa）',
        'sample_count': '每个条件的拉伸试验次数（n）',
        'sd_type': '报告的标准差（SD）',
        'record': '记录',
        'source_cell': '来源单元格位置',
        'protocol_heading': '制备、几何尺寸与试验方案',
        'protocol_geometry': '来源报告的狗骨形试样标称几何尺寸：总长 150 mm，标距 80 mm，厚度 3 mm，窄/宽段宽度 10/20 mm，夹距 110 mm。由横梁位移得到的工程应变使用包含过渡区的完整 110 mm，而非仅 80 mm 标距。局部应变率、尺寸公差和应力计算实测截面未知。不从几何尺寸重算应力。',
        'protocol_preparation': 'Creality K1 MAX FFF；水平构建；交替 +45°/−45° 栅格；100% 线性填充；五道轮廓；层高 0.2 mm；喷嘴 0.6 mm；喷嘴/热床 265/100 °C；内/外壁速度 60/60 mm/s；报告冷却设置 100%；报告试样质量 6.42 g。Step-Lab UD08 配集成试验箱进行拉伸。丝径 1.75 mm，供应线轴质量 0.5 kg。',
        'protocol_unknowns': '气氛和压力未知。数值相对湿度、试样含水量、温度传感器位置、稳定性容差和拉伸升温速率未知。不移用 DMA 升温速率。工程应变表述不确立工程应力。文章引用 ISO 527；符合性和文中标准网址未经独立核实。',
        'shared_metadata': '完整共同试验方案与条件元数据（保留规范键；null 表示未知）',
        'identity': '数据集与获准的共同试验方案组',
        'source_heading': '来源、版本与权利',
        'revision': '出版商 HTML 于 2026 年 10 月 3 日查阅，报告更新于 3 September 2026 02:53 CEST。未查阅 PDF，不主张 PDF 等同。缓存与实时内容差异位于未选入的表 4。仅选定的表 3 六组 UTS/SD 单元格在当前 HTML、目视核查和第二次转录间一致；这并非实验复现。',
        'adaptation': 'CC BY 4.0 改编说明：来源数值和 SD 字符串保持不变，重组并绘制为离散条件汇总值；SI 单位重新表达；整理说明为原创。不暗示出版商认可。排除制造商表 1、来源 PDF、图、截图、HTML 转储和原始测量。MIT 仅适用于原创项目贡献，不替代来源权利。',
        'si_heading': '单独列出的精确 SI 单位重表达',
        'si_notice': '1 MPa = 1000000 Pa 为精确换算。这些是同一组观测，不是新增绘图记录。单位缩放不增加测量精度，不使用几何或厚度。',
        'metadata_heading': '来源链与元数据完整性',
        'snapshot_notice': 'SHA-256 值标识所附目录元数据，并非出版商原始文件字节。JSON 导出保留完整科学快照与 null。',
        'evidence': '证据与组成部分位置',
        'source': '来源',
        'rights': '权利与署名',
        'details': '完整且通过校验的绘图数据包',
        'translation_notice': '科学表述及译文由机器辅助编写，尚未经独立的科学审校或母语审校。',
    },
    'ja': {
        'table_column': '表 3 · 温度列',
        'table_row': '表 3 の共通データ行',
        'table_container': '表コンテナ',
        'expanded_table': '展開表の位置',
        'record_cell': '記録 / 出典セル',
        'audit_details': '手順、来歴、SI およびスナップショットの全監査詳細',
        'metadata_exports': '完全な出典・記録スナップショット、null、正確な SI 値、メタデータダイジェストは JSON/CSV 出力と HTML 監査詳細に保持します。',
        'uncertainty_definition': '共通の不確かさの定義；各条件の SD 数値は正確な出典表に記載',
        'plot_temperature': '承認済みの六つの出典温度要約値と報告 SD のひげを出力する',
        'dataset_id': '承認済み温度観測データセットの正確な ID（必須）',
        'output': '温度図の JSON、CSV、SVG、HTML ファイルの出力先',
        'title': 'PA12 CF15：報告された試験槽温度条件下の引張強さ',
        'subtitle': '六つの離散的な出典要約値 · 出典報告の同一試験手順 · カタログ専用',
        'scope_heading': '図や数値を解釈する前にお読みください',
        'scope_protocol': '六つの条件要約値は、交互の +45°/−45° ラスターで水平 FFF 造形した Fiberlogy PA12 CF15 の一つの研究に由来します。出典報告の同一手順に限り、研究横断的・普遍的な材料の主張ではありません。共通メタデータは実際の同一調湿条件や材料不変性を証明しません。',
        'scope_temperature': 'X は 30 分の安定化後の報告された試験槽温度条件です。実際の試験片温度と温度の不確かさは未報告です。x 方向のひげがないことは不確かさゼロを意味せず、点の幅も温度精度を示しません。',
        'scope_statistic': '点は報告された UTS の中心値です。中心統計量、集約方法、応力の規約、応力計算の面積基準は不明です。中心値を平均値とは特定しません。',
        'scope_sd': '縦のひげは ± 報告された標準偏差（SD）を再現します。各条件で三回の引張試験が報告されていますが、反復生データとその独立性は未確認です。SD の計算式は不明です。SD は SEM、信頼区間、観測最小–最大範囲、厳密な限界、包含率の表明、完全な不確かさ予算ではありません。',
        'scope_preparation': '記載の作製法、形状、1 mm/min のクロスヘッド速度の手順に限ります。80 °C で 12 h の乾燥は実測含水量を確立せず、湿度・含水量は不明です。公称 15 wt.% の繊維と 100% 充填は実測組成や空隙率ゼロを証明しません。',
        'scope_limits': '補間、外挿、フィット、材料予測、順位付け、設計許容値、安全性の主張は行いません。転記・ソフトウェアの確認は独立した科学的検証ではありません。六つの独立した確認でもありません。',
        'glyph_legend': '点：報告された中心値。キャップ付き縦ひげ：中心値 ± 出典報告の SD；各条件 n=3 回の引張試験。SD は信頼区間や限界ではありません。温度の不確かさは未報告です。',
        'x_axis': '報告された試験槽温度条件（°C）',
        'y_axis': '原文報告の引張強さ UTS（MPa）',
        'plot_description': '六つの報告された試験槽条件に、同じ大きさの接続されない点と報告 SD のキャップ付き縦ひげを示します。正確な出典値と各条件の試験数は次の表にあります。',
        'axis_notice': '報告された条件はラベル付きの六点のみで、23–120 °C に及びます。15–125 °C の表示余白は観測や検証済み範囲を追加しません。Y の表示は 0–55 MPa；ゼロは視覚的基線で実験的限界ではありません。ひげ端点は中心値 ± SD の描画計算であり、追加観測ではありません。',
        'table_heading': '正確な出典セル',
        'table_notice': '表 3 の文字列は末尾のゼロを保持します。印刷桁数は分解能や正確さを確立しません。記録 ID と出典セル位置で各行を識別します。',
        'temperature': '試験槽ラベル（°C）',
        'source_value': '正確な出典セル（MPa）',
        'reported_sd': '報告 SD（MPa）',
        'sample_count': '各条件の引張試験数（n）',
        'sd_type': '報告された標準偏差（SD）',
        'record': '記録',
        'source_cell': '出典セル位置',
        'protocol_heading': '作製、形状および試験手順',
        'protocol_geometry': '出典報告の公称ダンベル形状：全長 150 mm、標点距離 80 mm、厚さ 3 mm、細部/広部の幅 10/20 mm、つかみ間隔 110 mm。クロスヘッド変位による工学ひずみは、80 mm の標点部だけでなく移行部を含む全 110 mm を使用します。局所ひずみ速度、寸法公差、応力計算の実測断面は不明です。形状から応力を再構成しません。',
        'protocol_preparation': 'Creality K1 MAX FFF；水平造形；交互の +45°/−45° ラスター；100% 線状充填；輪郭五周；層高 0.2 mm；ノズル 0.6 mm；ノズル/ベッド 265/100 °C；内/外壁速度 60/60 mm/s；報告冷却設定 100%；報告試験片質量 6.42 g。試験槽内蔵 Step-Lab UD08 で引張試験。フィラメント径 1.75 mm、供給スプール質量 0.5 kg。',
        'protocol_unknowns': '雰囲気と圧力は不明です。数値的な相対湿度、試験片含水量、温度センサー位置、安定性許容差、引張試験の昇温速度は不明です。DMA 昇温速度を転用しません。工学ひずみの記述は工学応力を確立しません。ISO 527 は引用されていますが、適合性と記事記載の規格 URL は独立確認されていません。',
        'shared_metadata': '共通手順・条件の完全なメタデータ（正規キーを保持；null は不明）',
        'identity': 'データセットと承認済み共通手順グループ',
        'source_heading': '出典、版および権利',
        'revision': '出版社 HTML を 2026 年 10 月 3 日に閲覧。報告更新日時は 3 September 2026 02:53 CEST。PDF は未閲覧で、同等性を主張しません。キャッシュと現行内容の相違は未選択の表 4 にあります。選択した表 3 の六つの UTS/SD セルのみ、現行 HTML、目視確認、二回目の転記で一致しています。実験の再現ではありません。',
        'adaptation': 'CC BY 4.0 による翻案：出典数値と SD 文字列を保持し、離散的条件要約として再編成・描画；SI 単位を再表現し、整理注記は独自作成です。出版社の支持を示しません。メーカー表 1、出典 PDF、図、スクリーンショット、HTML ダンプ、生測定を除外します。MIT は独自のプロジェクト貢献に適用し、出典の権利を置き換えません。',
        'si_heading': '別記した正確な SI 単位再表現',
        'si_notice': '1 MPa = 1000000 Pa は正確です。同じ観測であり追加の描画記録ではありません。単位変換は測定精度を増さず、形状や厚さを使いません。',
        'metadata_heading': '来歴とメタデータの完全性',
        'snapshot_notice': 'SHA-256 は同梱カタログメタデータを識別し、出版社の元資料のバイト列ではありません。JSON 出力に完全な科学的スナップショットと null を保持します。',
        'evidence': '根拠と資料内の位置',
        'source': '出典',
        'rights': '権利と帰属表示',
        'details': '検証済み描画バンドルの全内容',
        'translation_notice': '科学的表現と翻訳は機械支援で作成し、独立した科学的・母語による査読は受けていません。',
    },
    'de': {
        'table_column': 'Tabelle 3 · Temperaturspalte',
        'table_row': 'Gemeinsame Zeile in Tabelle 3',
        'table_container': 'Tabellencontainer',
        'expanded_table': 'Fundstelle der erweiterten Tabelle',
        'record_cell': 'Datensatz / Quellenzelle',
        'audit_details': 'Vollständige Prüfprotokoll-, Provenienz-, SI- und Snapshot-Auditdetails',
        'metadata_exports': 'Vollständige Quellen- und Datensatz-Snapshots, null-Werte, exakte SI-Werte und Metadatenprüfsummen bleiben in JSON-/CSV-Exporten und HTML-Auditdetails erhalten.',
        'uncertainty_definition': 'Gemeinsame Unsicherheitsdefinition; bedingungsspezifische SD-Werte stehen in der exakten Quellentabelle',
        'plot_temperature': 'Die sechs zugelassenen Temperaturzusammenfassungen mit berichteten SD-Whiskern exportieren',
        'dataset_id': 'Exakte ID des zugelassenen Temperatur-Beobachtungsdatensatzes (erforderlich)',
        'output': 'Ausgabeverzeichnis für Temperaturdiagramm-Dateien in JSON, CSV, SVG und HTML',
        'title': 'PA12 CF15: berichtete Zugfestigkeit bei Kammerbedingungen',
        'subtitle': 'Sechs diskrete Quellenzusammenfassungen · ein quellenberichtetes Protokoll · nur Katalog',
        'scope_heading': 'Vor der Interpretation von Diagramm und Werten lesen',
        'scope_protocol': 'Sechs Bedingungszusammenfassungen aus einer Studie zu horizontal FFF-gedrucktem Fiberlogy PA12 CF15 mit wechselndem +45°/−45°-Raster. Nur dasselbe quellenberichtete Protokoll; keine studienübergreifende oder allgemeingültige Materialaussage. Gemeinsame Metadaten beweisen weder identische Konditionierung noch Materialinvarianz.',
        'scope_temperature': 'X ist die berichtete Prüfkammer-Temperaturbedingung nach 30 Minuten Stabilisierung. Tatsächliche Probentemperatur und Temperaturunsicherheit sind nicht berichtet. Fehlende x-Whisker bedeuten keine Unsicherheit von null; die Punktbreite zeigt keine Temperaturpräzision.',
        'scope_statistic': 'Punkte zeigen berichtete zentrale UTS-Werte. Zentrale Statistik, Aggregation, Spannungskonvention und Spannungsbezugsfläche sind unbekannt; die Zentralwerte sind nicht als Mittelwerte identifiziert.',
        'scope_sd': 'Vertikale Whisker geben ± berichtete Standardabweichung (SD) wieder. Drei Zugversuche je Bedingung sind berichtet; Rohwiederholungen und ihre Unabhängigkeit sind ungeprüft. Die SD-Formel ist unbekannt. SD ist weder SEM, Konfidenzintervall, beobachteter Min–Max-Bereich, harte Grenze, Abdeckungsangabe noch vollständiges Unsicherheitsbudget.',
        'scope_preparation': 'Es gelten die spezifische Herstellung, Geometrie und das Protokoll mit 1 mm/min Traversengeschwindigkeit. Trocknung bei 80 °C für 12 h belegt keine gemessene Feuchte; Luft- und Materialfeuchte sind unbekannt. Deklarierte 15 wt.% Fasern und 100% Füllung belegen weder gemessene Zusammensetzung noch Porosität null.',
        'scope_limits': 'Keine Interpolation, Extrapolation, Anpassung, Materialvorhersage, Rangfolge, Bemessungswerte oder Sicherheitsbehauptung. Transkriptions- und Softwareprüfungen sind keine unabhängige wissenschaftliche Validierung. Die Zusammenfassungen sind keine sechs unabhängigen Bestätigungen.',
        'glyph_legend': 'Punkt: berichteter Zentralwert. Vertikaler Whisker mit Kappen: Zentralwert ± quellenberichtete SD; n=3 Zugversuche je Bedingung. SD ist kein Konfidenzintervall und keine Grenze. Temperaturunsicherheit ist nicht berichtet.',
        'x_axis': 'Berichtete Temperaturbedingung der Prüfkammer (°C)',
        'y_axis': 'Quellenberichtete Zugfestigkeit UTS (MPa)',
        'plot_description': 'Sechs unverbundene, gleich große Punkte an den sechs berichteten Kammerbedingungen, mit vertikalen Whiskern samt Kappen für berichtete SD. Exakte Quellenwerte und bedingungsbezogene Versuchszahlen stehen in der folgenden Tabelle.',
        'axis_notice': 'Berichtete Bedingungen: nur die sechs beschrifteten Punkte von 23–120 °C. Anzeigeränder von 15–125 °C liefern weder Beobachtungen noch validierten Bereich. Y-Anzeige 0–55 MPa: null ist eine visuelle Basislinie, keine experimentelle Grenze. Whisker-Endpunkte entstehen aus Zentralwert ± SD allein zur Darstellung, nicht als weitere Beobachtungen.',
        'table_heading': 'Exakte Quellenzellen',
        'table_notice': 'Die Zeichenfolgen aus Tabelle 3 behalten nachgestellte Nullen. Gedruckte Stellen belegen weder Auflösung noch Genauigkeit. Datensatz-IDs und Quellenzellfundstellen identifizieren jede Zeile.',
        'temperature': 'Kammerbeschriftung (°C)',
        'source_value': 'Exakte Quellenzelle (MPa)',
        'reported_sd': 'Berichtete SD (MPa)',
        'sample_count': 'Zugversuche je Bedingung (n)',
        'sd_type': 'Berichtete Standardabweichung (SD)',
        'record': 'Datensatz',
        'source_cell': 'Quellenzellfundstelle',
        'protocol_heading': 'Herstellung, Geometrie und Prüfprotokoll',
        'protocol_geometry': 'Quellenberichtete nominelle Schulterproben-Geometrie: Gesamtlänge 150 mm, Messlänge 80 mm, Dicke 3 mm, schmale/breite Breite 10/20 mm, Einspannabstand 110 mm. Die technische Dehnung aus Traversenweg nutzt volle 110 mm einschließlich Übergängen, nicht nur 80 mm Messlänge. Lokale Dehnrate, Maßtoleranzen und gemessener Spannungsquerschnitt sind unbekannt. Keine Spannungsrekonstruktion aus Geometrie.',
        'protocol_preparation': 'Creality K1 MAX FFF; horizontaler Aufbau; wechselndes +45°/−45°-Raster; 100% lineare Füllung; fünf Konturen; 0.2 mm Schichten; 0.6 mm Düse; Düse/Bett 265/100 °C; Innen-/Außenwandgeschwindigkeit 60/60 mm/s; berichtete Kühlung 100%; berichtete Probenmasse 6.42 g. Step-Lab UD08 mit integrierter Prüfkammer. Filamentdurchmesser 1.75 mm; gelieferte Spulenmasse 0.5 kg.',
        'protocol_unknowns': 'Atmosphäre und Druck sind unbekannt. Numerische relative Luftfeuchte, Probenfeuchte, Temperatursensorposition, Stabilitätstoleranz und Zugprüf-Heizrate sind unbekannt. Keine DMA-Heizrate wird übertragen. Technische Dehnung belegt keine technische Spannung. ISO 527 wird zitiert; Konformität und die im Artikel genannte Normen-URL wurden nicht unabhängig geprüft.',
        'shared_metadata': 'Vollständige gemeinsame Protokoll- und Bedingungsmetadaten (kanonische Schlüssel; null bleibt unbekannt)',
        'identity': 'Datensatz und zugelassene gemeinsame Protokollgruppe',
        'source_heading': 'Quelle, Version und Rechte',
        'revision': 'Verlags-HTML eingesehen am 3. Oktober 2026; berichtete Aktualisierung: 3 September 2026 02:53 CEST. PDF nicht geprüft; keine Gleichwertigkeitsbehauptung. Die Cache-/Live-Abweichung betrifft die nicht ausgewählte Tabelle 4. Nur die sechs ausgewählten UTS/SD-Zellen aus Tabelle 3 stimmen in aktuellem HTML, Sichtprüfung und zweiter Abschrift überein; dies ist keine experimentelle Reproduktion.',
        'adaptation': 'CC-BY-4.0-Bearbeitung: Quellennummern und SD-Zeichenfolgen unverändert, als diskrete Bedingungszusammenfassungen neu geordnet und dargestellt; SI-Einheiten umgerechnet; eigene Kuratoranmerkungen. Keine Billigung durch den Verlag impliziert. Herstellertabelle 1, Quellen-PDFs, Abbildungen, Screenshots, HTML-Abzüge und Rohmessungen sind ausgeschlossen. MIT gilt für eigene Projektbeiträge und ersetzt keine Quellenrechte.',
        'si_heading': 'Separate exakte SI-Umrechnung',
        'si_notice': '1 MPa = 1000000 Pa gilt exakt. Es sind dieselben Beobachtungen, keine weiteren dargestellten Datensätze. Einheitenskalierung erhöht keine Messpräzision und nutzt weder Geometrie noch Dicke.',
        'metadata_heading': 'Provenienz und Metadatenintegrität',
        'snapshot_notice': 'SHA-256-Werte identifizieren die beigefügten Katalogmetadaten, nicht die Bytes des Verlagsartefakts. Vollständige wissenschaftliche Snapshots und null-Werte bleiben im JSON-Export erhalten.',
        'evidence': 'Beleg und Komponentenfundstelle',
        'source': 'Quelle',
        'rights': 'Rechte und Quellenangabe',
        'details': 'Vollständiges validiertes Diagrammbündel',
        'translation_notice': 'Wissenschaftliche Formulierungen und Übersetzungen sind maschinell unterstützt und noch nicht unabhängig fachlich oder muttersprachlich geprüft.',
    },
}

SCOPE_KEYS = ('scope_protocol', 'scope_temperature', 'scope_statistic', 'scope_sd',
              'scope_preparation', 'scope_limits')


def labels(lang='en'):
    """Return a fresh label mapping and reject unsupported locale values."""
    from .observation_temperature_plot import _require
    _require(type(lang) is str and lang in LABELS, 'unsupported temperature-plot language')
    return dict(LABELS[lang])
