"""Authored presentation labels for source-ordered observation inspection.

These working translations describe the catalog's existing interpretation and
limits. They do not translate source passages or supply scientific metadata.
Keep every locale complete; labels must not be filled by English fallbacks.
"""


LABELS = {
    "en": {
        'pa12_strength': '3D ultimate tensile strength as reported',
        'pa12_classification': 'Source-reported · experiment-derived tensile-test summary · catalog-only',
        'pa12_identity': 'Specific printed composite · 3D pressure dimension',
        'pa12_dataset': 'Dataset',
        'pa12_protocol': 'Protocol',
        'pa12_temperature': 'Reported chamber test condition',
        'pa12_temperature_basis': 'Temperature basis: reported chamber test condition; not verified specimen temperature',
        'pa12_temperature_warning': 'The displayed temperature is the reported chamber condition after 30 min stabilization. Direct specimen temperature, sensor location and stability tolerance are unknown. No DMA heating ramp is transferred to this tensile test.',
        'pa12_process_warning': 'This is horizontal FFF Fiberlogy PA12 CF15 with alternating +45°/-45° raster, filament dried at 80 °C for 12 h, and crosshead rate 1 mm/min. The 100% infill setting is not measured zero porosity; declared 15 wt.% carbon fiber is not an assayed fraction. Actual moisture and numeric relative humidity are unknown; drying does not establish a measured dry state. Local strain rate is unknown.',
        'pa12_stress_statistic_warning': 'UTS is retained as reported. Stress convention, stress-area basis, mathematical extraction criterion, central-statistic name and aggregation convention are unknown. Engineering-strain wording does not establish engineering stress.',
        'pa12_sd_count_warning': 'Three tensile tests are reported per temperature condition. ± is reported standard deviation (SD), not SEM, a confidence interval, endpoints, bounds or a full uncertainty budget. The SD formula and replicate independence are unknown. Raw replicate and stress-area reanalysis are unavailable.',
        'pa12_scope_warning': 'These six conditions belong to one study and protocol, not six independent confirmations. No interpolation, extrapolation, continuous temperature law, ranking, universal strength bound or design allowable is supported.',
        'pa12_reported_display': 'Catalog display in reported units',
        'pa12_reported_notice': 'Exact reported decimal strings are preserved; printed digits do not establish measurement resolution or accuracy.',
        'pa12_si_display': 'Exact SI unit re-expression',
        'pa12_si_notice': '1 MPa = 1000000 Pa exactly. Unit scaling adds no measurement precision and uses no geometry or thickness; it is not another observation.',
        'pa12_material': 'Material and preparation metadata',
        'pa12_method': 'Tensile protocol and nominal geometry',
        'pa12_conditions': 'Temperature, humidity and other conditions',
        'pa12_counts': 'Test counts and aggregation metadata',
        'pa12_source_version': 'Inspected source version and limits',
        'pa12_version_warning': 'Publisher HTML was inspected on 2026-10-03; its reported update is 3 September 2026 02:53 CEST. The PDF was not inspected and equivalence is not asserted. An unselected Table 4 cached/live discrepancy remains explicit. Only the six selected Table 3 UTS/SD cells agree across current HTML, visual checking and a second transcription; this is not independent experimental reproduction.',
        'pa12_standard_warning': 'ISO 527 is the article’s cited standard. Compliance and the article-reported standards URL were not independently verified; that URL is source text, not a verified link.',
        'pa12_rights_warning': 'Table 3 facts are attributed to Ciganas, Kalinauskis and Cigane (2026), DOI 10.3390/polym18050563, under the article’s verified CC BY 4.0 license. Values were reorganized into discrete observations with exact unit re-expression and original curator notes. Manufacturer-provided Table 1 is excluded.',
        'pa12_cell': 'Selected table cell',
        "title": "Observation inspection",
        "subtitle": "Inspection only, in source order; no matched-condition comparison.",
        "policy": "No ranking, aggregation or overlay. Stiffness and strength remain separate quantities; unknown conditions do not establish equivalence.",
        "translation_notice": "Scientific wording and translations are machine-assisted and have not received independent scientific or native-language review.",
        "snapshot_notice": "SHA-256 digests identify the bundled catalog metadata, not the paper bytes. Source records have no individual version field.",
        "rights_notice": "No source PDFs, full text, figures, screenshots or raw measurement data are redistributed. Permission to read a source does not establish permission to reuse it; artifact-specific rights remain applicable.",
        "classification": "Source-reported · experiment-derived · model-dependent · catalog-only",
        "normalized": "Normalized catalog display",
        "normalized_notice": "Exact stored N/m values displayed from the catalog; this display is not a verbatim source quotation.",
        "source_wording": "Original source wording",
        "source_wording_absent": "No source-value wording is stored for this record; no quotation is reconstructed.",
        "original_context": "Original source context may mention three-dimensional units; those are not additional selected results.",
        "identity": "Identity",
        "quantity": "Quantity",
        "study": "Study",
        "record_version": "Record version",
        "uncertainty": "Uncertainty meaning",
        "uncertainty_evidence": "Evidence for uncertainty meaning",
        "statistic": "Central-value statistic",
        "statistic_unknown": "Exact central-statistic label unspecified; do not assume a mean.",
        "sample": "Sample information and count scope",
        "conditions": "Known and unknown conditions",
        "model": "Source inference model",
        "evidence": "Value evidence and source locator",
        "verification": "Inspection and verification scope",
        "rights": "Source rights and reuse limits",
        "details": "Full source and record details",
        "source_links": "Source links",
        "unknown": "Unknown / not established",
        "group_study": "Grouped by study",
        "group_quantity": "Grouped by quantity",
        "record": "Record",
        "source": "Source",
        "catalog_schema": "Catalog schema version",
        "digest": "Metadata snapshot SHA-256",
        "stiffness": "2D in-plane stiffness",
        "strength": "2D breaking strength",
        "no_comparison": "Associated summaries from one study are not independent confirmations. This view establishes no comparability, theoretical bounds or engineering allowables.",
        "command": "Inspect catalog-only experimental observations without evaluating or ranking them",
        "inspect": "Export source-ordered observation inspection views",
        "output": "Output directory for JSON, CSV, SVG and HTML inspection files",
        "ids": "Exact record IDs; repeat the option to select several records",
        "id": "Exact record ID; repeat to select several records",
        "source_filter": "Select records from this exact source ID",
        "source_id": "Exact source ID filter",
        "quantity_filter": "Select one supported observation quantity",
        "group": "Group navigation by study or quantity; no change in scientific interpretation",
        "group_by": "Group by study or quantity, retaining source order within each group",
        "primary_warning": "Read before interpreting the value",
        "graphene_warning": "The source-reported ± has an unverified statistical meaning. It is not established as SD, SEM, a confidence interval or a hard bound.",
        "mos2_warning": "Source-reported values retain an unresolved printed-q discrepancy: the actual fitted q is unknown, and no refit or correction was performed. Strength also inherits the fitted-stiffness and source-model caveat.",
        "hbn_strength_warning": "Source-reported nonlinear FEM strength is volume-averaged stress beneath the indenter; the exact central-statistic label and stress component are unspecified. It is not uniform-tension strength, a local maximum or the maximum Von Mises stress in Supplementary Figure S5.",
        "hbn_stiffness_warning": "Source-reported stiffness comes from a circular-membrane force–deflection fit. This inference is distinct from the nonlinear FEM strength reduction.",
        "sd_warning": "Reported standard deviation (SD) is not SEM, a confidence interval, 68% coverage, a hard bound or a full uncertainty budget. Averaging and replicate weights, and coverage, are unknown.",
    },
    "zh": {
        'pa12_strength': '来源报告的三维极限拉伸强度',
        'pa12_classification': '来源报告 · 拉伸试验推导的汇总值 · 仅用于目录',
        'pa12_identity': '特定打印复合材料 · 三维压力量纲',
        'pa12_dataset': '数据集',
        'pa12_protocol': '试验方案',
        'pa12_temperature': '来源报告的试验腔温度条件',
        'pa12_temperature_basis': '温度依据：来源报告的试验腔条件；并非经核实的试样温度',
        'pa12_temperature_warning': '所示温度是稳定 30 min 后来源报告的试验腔条件。直接试样测温、传感器位置及稳定性容差未知。不将 DMA 的升温速率移用于此拉伸试验。',
        'pa12_process_warning': '此记录对应水平 FFF 打印的 Fiberlogy PA12 CF15，采用交替 +45°/-45° 栅格；丝材在 80 °C 下干燥 12 h，横梁速度为 1 mm/min。100% 填充设置并不等于测得零孔隙率；标称 15 wt.% 碳纤维并非实测含量。实际含水量和数值相对湿度未知；干燥处理不确立实测干态。局部应变率未知。',
        'pa12_stress_statistic_warning': '保留来源报告的 UTS。应力约定、应力计算面积依据、数学提取准则、中心统计量名称及汇总方式未知。工程应变的表述并不能确立工程应力。',
        'pa12_sd_count_warning': '来源报告每个温度条件进行了三次拉伸试验。± 为报告的标准差（SD），并非均值标准误（SEM）、置信区间、端点、界限或完整不确定度预算。SD 计算公式和重复试验独立性未知。无法重分析原始重复试验或应力面积数据。',
        'pa12_scope_warning': '六个条件属于同一研究和试验方案，并非六次独立验证。不支持插值、外推、连续温度定律、排名、普适强度界限或工程许用值。',
        'pa12_reported_display': '按报告单位显示的目录数值',
        'pa12_reported_notice': '保留报告中的精确小数字符串；印出位数不确立测量分辨率或准确度。',
        'pa12_si_display': '精确的 SI 单位重表达',
        'pa12_si_notice': '1 MPa = 1000000 Pa 为精确换算。单位缩放不增加测量精度，不使用几何或厚度，也不构成另一条观测。',
        'pa12_material': '材料与制备元数据',
        'pa12_method': '拉伸方案与标称几何尺寸',
        'pa12_conditions': '温度、湿度及其他条件',
        'pa12_counts': '试验次数与汇总元数据',
        'pa12_source_version': '已查阅的来源版本与限制',
        'pa12_version_warning': '出版商 HTML 于 2026-10-03 查阅，报告的更新时间为 3 September 2026 02:53 CEST。未查阅 PDF，也不主张两者等同。明确保留未选入的表 4 缓存与实时内容差异。仅选入的表 3 六组 UTS/SD 单元格在当前 HTML、目视核查及第二次转录间一致；这并非独立实验复现。',
        'pa12_standard_warning': 'ISO 527 为文章引用的标准。未独立核实符合性或文章报告的标准网址；该网址属于来源文本，并非已核实的链接。',
        'pa12_rights_warning': '表 3 事实归属于 Ciganas、Kalinauskis 和 Cigane（2026），DOI 10.3390/polym18050563，遵循文章已核实的 CC BY 4.0 许可。数值重组为离散观测，附精确单位重表达及原创整理说明。排除制造商提供的表 1。',
        'pa12_cell': '选定表格单元格',
        "title": "观测记录查阅",
        "subtitle": "仅供查阅，按来源顺序排列；不作同条件比较。",
        "policy": "不排名、不合并、不叠加。刚度与强度仍是不同物理量；条件未知不意味着条件等同。",
        "translation_notice": "科学表述及译文由机器辅助编写，尚未经独立的科学审校或母语审校。",
        "snapshot_notice": "SHA-256 摘要标识所附目录元数据，而非论文文件字节。来源记录没有单独的版本字段。",
        "rights_notice": "不再分发来源 PDF、全文、图件、截图或原始测量数据。可阅读来源不代表获得复用许可；仍须遵守各资料的具体权利限制。",
        "classification": "来源报告 · 实验推导 · 依赖模型 · 仅用于目录",
        "normalized": "规范化目录显示",
        "normalized_notice": "按目录中存储的精确数值以 N/m 显示；此显示不是来源原文的逐字引文。",
        "source_wording": "来源原始表述",
        "source_wording_absent": "此记录未存储来源的数值原文；不据此重构引文。",
        "original_context": "来源原始上下文可能提及三维单位；这些不是额外选入的结果。",
        "identity": "记录标识",
        "quantity": "物理量",
        "study": "研究",
        "record_version": "记录版本",
        "uncertainty": "不确定度含义",
        "uncertainty_evidence": "不确定度含义的依据",
        "statistic": "中心值统计量",
        "statistic_unknown": "中心统计量的确切名称未明确；不得假定为平均值。",
        "sample": "样本信息与计数范围",
        "conditions": "已知与未知条件",
        "model": "来源推断模型",
        "evidence": "数值依据与来源位置",
        "verification": "查阅与核实范围",
        "rights": "来源权利与复用限制",
        "details": "完整来源与记录详情",
        "source_links": "来源链接",
        "unknown": "未知／尚未确定",
        "group_study": "按研究分组",
        "group_quantity": "按物理量分组",
        "record": "记录",
        "source": "来源",
        "catalog_schema": "目录模式版本",
        "digest": "元数据快照 SHA-256",
        "stiffness": "二维面内刚度",
        "strength": "二维断裂强度",
        "no_comparison": "同一研究中相互关联的汇总值不是独立验证。此视图不确立可比性、理论界限或工程许用值。",
        "command": "查阅仅用于目录的实验观测记录，不执行计算或排名",
        "inspect": "导出按来源顺序排列的观测记录查阅视图",
        "output": "JSON、CSV、SVG 和 HTML 查阅文件的输出目录",
        "ids": "精确记录 ID；重复此选项可选择多条记录",
        "id": "精确记录 ID；重复使用可选择多条记录",
        "source_filter": "选择来自此精确来源 ID 的记录",
        "source_id": "精确来源 ID 筛选条件",
        "quantity_filter": "选择一种受支持的观测物理量",
        "group": "按研究或物理量组织导航；不改变科学解释",
        "group_by": "按研究或物理量分组，组内保留来源顺序",
        "primary_warning": "解释数值前请先阅读",
        "graphene_warning": "来源报告的 ± 的统计含义尚未核实。不能将其认定为标准差（SD）、均值标准误（SEM）、置信区间或硬界限。",
        "mos2_warning": "保留来源报告值，其中印出的 q 存在尚未解决的不一致：实际拟合所用的 q 未知，未重新拟合或修正。强度还继承拟合刚度及来源模型的限制。",
        "hbn_strength_warning": "来源报告的非线性有限元强度是压头下方应力的体积平均；中心统计量的确切名称及应力分量未明确。它不是均匀拉伸强度、局部最大值或补充图 S5 中的最大 Von Mises 应力。",
        "hbn_stiffness_warning": "来源报告的刚度来自圆膜力–挠度关系拟合。此推断不同于非线性有限元强度归约。",
        "sd_warning": "报告的标准差（SD）不是均值标准误（SEM）、置信区间、68% 覆盖范围、硬界限或完整不确定度预算。平均方式、重复测量权重及覆盖范围未知。",
    },
    "ja": {
        'pa12_strength': '出典が報告した三次元の極限引張強度',
        'pa12_classification': '出典の報告値 · 引張試験から導出した要約 · カタログ専用',
        'pa12_identity': '特定の造形複合材 · 三次元の圧力次元',
        'pa12_dataset': 'データセット',
        'pa12_protocol': '試験手順',
        'pa12_temperature': '報告された試験槽の温度条件',
        'pa12_temperature_basis': '温度の根拠：報告された試験槽条件。検証済みの試料温度ではありません',
        'pa12_temperature_warning': '表示温度は 30 min の安定化後に報告された試験槽条件です。試料の直接測温、センサー位置、安定性の許容差は不明です。DMA の昇温速度をこの引張試験へ転用しません。',
        'pa12_process_warning': '対象は水平 FFF 造形の Fiberlogy PA12 CF15 で、交互の +45°/-45° ラスターを用い、フィラメントを 80 °C で 12 h 乾燥し、クロスヘッド速度は 1 mm/min です。100% インフィル設定は実測空隙率ゼロを意味せず、公称炭素繊維 15 wt.% は分析値ではありません。実際の含水量と数値の相対湿度は不明で、乾燥処理は実測乾燥状態を確立しません。局所ひずみ速度は不明です。',
        'pa12_stress_statistic_warning': 'UTS は出典の報告どおり保持します。応力の規約、応力面積の基準、数学的な抽出基準、中心統計量の名称、集約方法は不明です。工学ひずみという記述から工学応力とは確定できません。',
        'pa12_sd_count_warning': '温度条件ごとに三回の引張試験が報告されています。± は報告標準偏差（SD）であり、平均の標準誤差（SEM）、信頼区間、端点、限界、完全な不確かさ予算ではありません。SD の計算式と反復試験の独立性は不明です。生の反復値や応力面積データの再解析はできません。',
        'pa12_scope_warning': '六つの条件は同一研究・手順に属し、六つの独立した確認ではありません。補間、外挿、連続温度則、順位付け、普遍的強度限界、設計許容値は裏付けられません。',
        'pa12_reported_display': '報告単位によるカタログ表示',
        'pa12_reported_notice': '報告された小数文字列を正確に保持します。印刷桁数は測定の分解能や正確さを確立しません。',
        'pa12_si_display': '正確な SI 単位への再表現',
        'pa12_si_notice': '1 MPa = 1000000 Pa は正確な換算です。単位換算は測定精度を追加せず、形状や厚さを用いず、別の観測を意味しません。',
        'pa12_material': '材料と造形準備のメタデータ',
        'pa12_method': '引張試験手順と公称形状',
        'pa12_conditions': '温度・湿度とその他の条件',
        'pa12_counts': '試験回数と集約のメタデータ',
        'pa12_source_version': '確認した出典版と制約',
        'pa12_version_warning': '出版社 HTML を 2026-10-03 に確認し、報告更新日時は 3 September 2026 02:53 CEST です。PDF は未確認で、同等性を主張しません。未選択の表 4 にはキャッシュと現行版の相違があります。選択した表 3 の六組の UTS/SD セルのみ、現行 HTML、目視確認、二回目の転記で一致しました。独立した実験再現ではありません。',
        'pa12_standard_warning': 'ISO 527 は記事が引用した規格です。適合性と記事記載の規格 URL は独立に検証していません。この URL は出典の文章であり、検証済みリンクではありません。',
        'pa12_rights_warning': '表 3 の事実は Ciganas、Kalinauskis、Cigane（2026）、DOI 10.3390/polym18050563 に帰属し、記事で確認した CC BY 4.0 の下にあります。数値を離散観測に整理し、正確な単位再表現と独自の注記を加えました。製造元提供の表 1 は除外しています。',
        'pa12_cell': '選択した表のセル',
        "title": "観測記録の確認",
        "subtitle": "出典順の確認専用表示です。同一条件での比較は行いません。",
        "policy": "順位付け、集約、重ね合わせは行いません。剛性と強度は別の物理量であり、条件不明は条件の同等性を示しません。",
        "translation_notice": "科学的な記述と翻訳は機械支援で作成しており、独立した科学的査読や母語話者による校閲は受けていません。",
        "snapshot_notice": "SHA-256 ダイジェストは同梱したカタログのメタデータを識別するもので、論文ファイルのバイト列を識別するものではありません。出典記録には個別のバージョン欄がありません。",
        "rights_notice": "出典 PDF、全文、図、スクリーンショット、測定の生データは再配布しません。閲覧できることは再利用の許可を意味せず、各資料の権利条件が適用されます。",
        "classification": "出典の報告値 · 実験から導出 · モデル依存 · カタログ専用",
        "normalized": "正規化したカタログ表示",
        "normalized_notice": "カタログに保存した正確な値を N/m で表示します。この表示は出典の逐語引用ではありません。",
        "source_wording": "出典の原文表記",
        "source_wording_absent": "この記録には値の出典原文を保存していません。引用文を再構成しません。",
        "original_context": "出典原文の文脈には三次元の単位が含まれる場合がありますが、追加の選定結果ではありません。",
        "identity": "識別情報",
        "quantity": "物理量",
        "study": "研究",
        "record_version": "記録のバージョン",
        "uncertainty": "不確かさの意味",
        "uncertainty_evidence": "不確かさの意味を示す根拠",
        "statistic": "中心値の統計量",
        "statistic_unknown": "中心統計量の正確な名称は未指定です。平均値とは仮定しません。",
        "sample": "試料情報と計数の範囲",
        "conditions": "既知・未知の条件",
        "model": "出典の推定モデル",
        "evidence": "値の根拠と出典内の位置",
        "verification": "資料確認と検証の範囲",
        "rights": "出典の権利と再利用の制限",
        "details": "出典と記録の全詳細",
        "source_links": "出典リンク",
        "unknown": "不明／未確立",
        "group_study": "研究別の表示",
        "group_quantity": "物理量別の表示",
        "record": "記録",
        "source": "出典",
        "catalog_schema": "カタログスキーマのバージョン",
        "digest": "メタデータのスナップショット SHA-256",
        "stiffness": "二次元面内剛性",
        "strength": "二次元破断強度",
        "no_comparison": "同じ研究の関連する要約値は独立した検証ではありません。この表示は比較可能性、理論的限界、設計許容値を確立しません。",
        "command": "カタログ専用の実験観測記録を、計算評価や順位付けをせずに確認する",
        "inspect": "出典順の観測記録確認ビューを出力する",
        "output": "JSON、CSV、SVG、HTML の確認用ファイルの出力先ディレクトリ",
        "ids": "正確な記録 ID。このオプションを繰り返すと複数選択できます",
        "id": "正確な記録 ID。繰り返し指定で複数選択できます",
        "source_filter": "指定した正確な出典 ID の記録を選択する",
        "source_id": "正確な出典 ID による絞り込み",
        "quantity_filter": "対応する観測物理量を一つ選択する",
        "group": "研究または物理量で表示をまとめる。科学的解釈は変わりません",
        "group_by": "研究または物理量でまとめ、各グループ内では出典順を維持する",
        "primary_warning": "値を解釈する前にお読みください",
        "graphene_warning": "出典が報告する ± の統計的な意味は未確認です。標準偏差（SD）、平均の標準誤差（SEM）、信頼区間、厳密な限界とは確定していません。",
        "mos2_warning": "出典の報告値には、印刷された q の未解決の不整合が残ります。実際のフィットに用いた q は不明で、再フィットや補正は行っていません。強度にもフィットした剛性と出典モデルの制約が引き継がれます。",
        "hbn_strength_warning": "出典の非線形有限要素解析（FEM）による強度は圧子直下の応力の体積平均であり、中心統計量の正確な名称と応力成分は未指定です。一様引張強度、局所最大値、補足図 S5 の最大 Von Mises 応力ではありません。",
        "hbn_stiffness_warning": "出典の剛性報告値は円形膜の力–たわみ関係のフィットから得られています。この推定は非線形 FEM による強度の算出とは異なります。",
        "sd_warning": "報告された標準偏差（SD）は平均の標準誤差（SEM）、信頼区間、68% の包含、厳密な限界、完全な不確かさ予算ではありません。平均化の方法、反復値の重み付け、包含範囲は不明です。",
    },
    "de": {
        'pa12_strength': '3D-Zugfestigkeit wie in der Quelle berichtet',
        'pa12_classification': 'Quellenangabe · aus Zugversuchen abgeleitete Zusammenfassung · nur für den Katalog',
        'pa12_identity': 'Spezifischer gedruckter Verbundwerkstoff · 3D-Druckdimension',
        'pa12_dataset': 'Datensatzgruppe',
        'pa12_protocol': 'Prüfprotokoll',
        'pa12_temperature': 'Berichtete Temperaturbedingung der Prüfkammer',
        'pa12_temperature_basis': 'Temperaturbasis: berichtete Prüfkammerbedingung; keine verifizierte Probentemperatur',
        'pa12_temperature_warning': 'Die angezeigte Temperatur ist die berichtete Kammerbedingung nach 30 min Stabilisierung. Direkte Probentemperatur, Sensorposition und Stabilitätstoleranz sind unbekannt. Keine DMA-Heizrampe wird auf den Zugversuch übertragen.',
        'pa12_process_warning': 'Dies ist horizontal FFF-gedrucktes Fiberlogy PA12 CF15 mit wechselndem +45°/-45° Raster, bei 80 °C für 12 h getrocknetem Filament und 1 mm/min Traversengeschwindigkeit. Die 100%-Füllung belegt keine gemessene Porosität von null; deklarierte 15 wt.% Kohlenstofffasern sind kein analysierter Anteil. Tatsächliche Feuchte und numerische relative Luftfeuchte sind unbekannt; Trocknung belegt keinen gemessenen Trockenzustand. Die lokale Dehnrate ist unbekannt.',
        'pa12_stress_statistic_warning': 'UTS bleibt wie berichtet erhalten. Spannungskonvention, Bezugsfläche, mathematisches Auswertekriterium, Bezeichnung der zentralen Statistik und Aggregationsverfahren sind unbekannt. Die Angabe technischer Dehnung belegt keine technische Spannung.',
        'pa12_sd_count_warning': 'Pro Temperaturbedingung werden drei Zugversuche berichtet. ± ist die berichtete Standardabweichung (SD), kein Standardfehler (SEM), Konfidenzintervall, Endpunkt, Grenzwert oder vollständiges Unsicherheitsbudget. SD-Formel und Unabhängigkeit der Wiederholungen sind unbekannt. Rohwerte und Spannungsquerschnitt können nicht erneut ausgewertet werden.',
        'pa12_scope_warning': 'Diese sechs Bedingungen gehören zu einer Studie und einem Protokoll, nicht zu sechs unabhängigen Bestätigungen. Interpolation, Extrapolation, kontinuierliches Temperaturgesetz, Rangfolge, universelle Festigkeitsgrenze oder Bemessungswert sind nicht gestützt.',
        'pa12_reported_display': 'Kataloganzeige in berichteten Einheiten',
        'pa12_reported_notice': 'Die berichteten Dezimalzeichenfolgen bleiben exakt erhalten; gedruckte Stellen belegen weder Messauflösung noch Genauigkeit.',
        'pa12_si_display': 'Exakte Umrechnung in SI-Einheiten',
        'pa12_si_notice': '1 MPa = 1000000 Pa gilt exakt. Die Einheitenskalierung erhöht keine Messpräzision und nutzt weder Geometrie noch Dicke; sie ist keine weitere Beobachtung.',
        'pa12_material': 'Material- und Fertigungsmetadaten',
        'pa12_method': 'Zugprüfprotokoll und nominelle Geometrie',
        'pa12_conditions': 'Temperatur, Luftfeuchte und weitere Bedingungen',
        'pa12_counts': 'Versuchszahlen und Aggregationsmetadaten',
        'pa12_source_version': 'Eingesehene Quellenversion und Grenzen',
        'pa12_version_warning': 'Das Verlags-HTML wurde am 2026-10-03 eingesehen; die berichtete Aktualisierung ist 3 September 2026 02:53 CEST. Das PDF wurde nicht geprüft; Gleichwertigkeit wird nicht behauptet. Eine Abweichung zwischen Cache und Live-Fassung der nicht ausgewählten Tabelle 4 bleibt ausdrücklich vermerkt. Nur die sechs gewählten UTS/SD-Zellen aus Tabelle 3 stimmen zwischen aktuellem HTML, Sichtprüfung und zweiter Abschrift überein; dies ist keine unabhängige experimentelle Reproduktion.',
        'pa12_standard_warning': 'ISO 527 ist die im Artikel zitierte Norm. Konformität und die dort genannte Normen-URL wurden nicht unabhängig verifiziert; die URL ist Quellentext, kein geprüfter Link.',
        'pa12_rights_warning': 'Die Fakten aus Tabelle 3 werden Ciganas, Kalinauskis und Cigane (2026), DOI 10.3390/polym18050563, unter der verifizierten CC-BY-4.0-Lizenz des Artikels zugeschrieben. Werte wurden zu diskreten Beobachtungen mit exakter Einheitenumrechnung und eigenen Anmerkungen geordnet. Herstellertabelle 1 ist ausgeschlossen.',
        'pa12_cell': 'Ausgewählte Tabellenzelle',
        "title": "Beobachtungen prüfen",
        "subtitle": "Nur zur Einsicht, in Quellenreihenfolge; kein Vergleich bei gleichen Bedingungen.",
        "policy": "Keine Rangfolge, Zusammenfassung von Werten oder Überlagerung. Steifigkeit und Festigkeit bleiben getrennte Größen; unbekannte Bedingungen belegen keine Gleichwertigkeit.",
        "translation_notice": "Die wissenschaftlichen Texte und Übersetzungen wurden maschinell unterstützt erstellt und noch nicht unabhängig fachlich oder muttersprachlich geprüft.",
        "snapshot_notice": "SHA-256-Prüfsummen identifizieren die beigefügten Katalogmetadaten, nicht die Bytes der Publikation. Quellen haben kein eigenes Versionsfeld.",
        "rights_notice": "Quellen-PDFs, Volltexte, Abbildungen, Screenshots und Rohmessdaten werden nicht weitergegeben. Lesezugang belegt keine Erlaubnis zur Nachnutzung; die Rechte des jeweiligen Dokuments gelten weiterhin.",
        "classification": "Quellenangabe · experimentell abgeleitet · modellabhängig · nur für den Katalog",
        "normalized": "Normalisierte Kataloganzeige",
        "normalized_notice": "Anzeige der exakt gespeicherten Katalogwerte in N/m; diese Anzeige ist kein wörtliches Quellenzitat.",
        "source_wording": "Originaler Wortlaut der Quelle",
        "source_wording_absent": "Für diesen Datensatz ist kein Quellenwortlaut zum Wert gespeichert; ein Zitat wird nicht rekonstruiert.",
        "original_context": "Der ursprüngliche Quellenkontext kann dreidimensionale Einheiten nennen; diese sind keine zusätzlichen ausgewählten Ergebnisse.",
        "identity": "Identität",
        "quantity": "Physikalische Größe",
        "study": "Studie",
        "record_version": "Datensatzversion",
        "uncertainty": "Bedeutung der Unsicherheit",
        "uncertainty_evidence": "Beleg zur Bedeutung der Unsicherheit",
        "statistic": "Statistik des zentralen Werts",
        "statistic_unknown": "Die genaue Bezeichnung der zentralen Statistik ist nicht angegeben; keinen Mittelwert annehmen.",
        "sample": "Probenangaben und Geltungsbereich der Zählungen",
        "conditions": "Bekannte und unbekannte Bedingungen",
        "model": "Ableitungsmodell der Quelle",
        "evidence": "Wertbeleg und Fundstelle",
        "verification": "Umfang der Einsicht und Prüfung",
        "rights": "Quellenrechte und Grenzen der Nachnutzung",
        "details": "Vollständige Quellen- und Datensatzdetails",
        "source_links": "Quellenlinks",
        "unknown": "Unbekannt / nicht belegt",
        "group_study": "Nach Studie gruppiert",
        "group_quantity": "Nach Größe gruppiert",
        "record": "Datensatz",
        "source": "Quelle",
        "catalog_schema": "Katalogschemaversion",
        "digest": "SHA-256 des Metadatenstands",
        "stiffness": "2D-Steifigkeit in der Ebene",
        "strength": "2D-Bruchfestigkeit",
        "no_comparison": "Zugehörige Zusammenfassungen einer Studie sind keine unabhängigen Bestätigungen. Diese Ansicht belegt weder Vergleichbarkeit noch theoretische Grenzen oder Bemessungswerte.",
        "command": "Experimentelle Katalogbeobachtungen ohne Berechnung oder Rangfolge prüfen",
        "inspect": "Beobachtungsansichten in Quellenreihenfolge exportieren",
        "output": "Ausgabeverzeichnis für JSON-, CSV-, SVG- und HTML-Prüfansichten",
        "ids": "Exakte Datensatz-IDs; Option für mehrere Datensätze wiederholen",
        "id": "Exakte Datensatz-ID; für mehrere Datensätze wiederholen",
        "source_filter": "Datensätze mit dieser exakten Quellen-ID auswählen",
        "source_id": "Filter auf eine exakte Quellen-ID",
        "quantity_filter": "Eine unterstützte Beobachtungsgröße auswählen",
        "group": "Navigation nach Studie oder Größe gruppieren; wissenschaftliche Interpretation bleibt unverändert",
        "group_by": "Nach Studie oder Größe gruppieren; Quellenreihenfolge innerhalb jeder Gruppe beibehalten",
        "primary_warning": "Vor der Interpretation des Werts lesen",
        "graphene_warning": "Die statistische Bedeutung des in der Quelle berichteten ± ist ungeprüft. Es ist nicht als Standardabweichung (SD), Standardfehler (SEM), Konfidenzintervall oder harte Grenze belegt.",
        "mos2_warning": "Die Quellenwerte behalten einen ungeklärten Widerspruch beim gedruckten q bei: Das tatsächlich beim Fit verwendete q ist unbekannt; es gab keinen neuen Fit und keine Korrektur. Auch die Festigkeit übernimmt den Vorbehalt zur angepassten Steifigkeit und zum Quellenmodell.",
        "hbn_strength_warning": "Die in der Quelle berichtete nichtlineare FEM-Festigkeit ist eine volumengemittelte Spannung unter dem Eindringkörper; die genaue zentrale Statistik und Spannungskomponente sind nicht angegeben. Sie ist keine gleichförmige Zugfestigkeit, kein lokales Maximum und nicht die maximale Von-Mises-Spannung aus Ergänzungsabbildung S5.",
        "hbn_stiffness_warning": "Die Steifigkeitsangabe der Quelle stammt aus einem Fit der Kraft-Durchbiegungs-Beziehung einer Kreismembran. Diese Ableitung unterscheidet sich von der nichtlinearen FEM-Auswertung der Festigkeit.",
        "sd_warning": "Die berichtete Standardabweichung (SD) ist kein Standardfehler (SEM), Konfidenzintervall, Beleg für 68% Abdeckung, harte Grenze oder vollständiges Unsicherheitsbudget. Mittelungsverfahren, Gewichtung der Wiederholungen und Abdeckung sind unbekannt.",
    },
}
