"""Authored four-language PAHT-CF inspection/catalog wording.

These are working translations, not source quotations or independent review.
The source's medians and SD remain separate; SD units are contextual inference.
"""

PAHT_DISPLAY_BASIS = 'catalog_exact_reported_median_and_separate_sd_strings_with_contextually_inferred_sd_unit'
PAHT_CAVEATS = (
    'paht_temperature_warning', 'paht_process_warning', 'paht_stress_warning',
    'paht_sd_count_warning', 'paht_sd_unit_warning', 'paht_geometry_warning',
    'paht_scope_warning', 'paht_version_warning', 'paht_rights_warning',
)

PAHT_LABELS = {
    'en': {
        'paht_classification': 'Source-reported · experiment-derived tensile-test summary · catalog-only',
        'paht_identity': 'Bambu Lab PAHT-CF · annealed · flat FFF · ±45° orientation · 3D pressure dimension',
        'paht_dataset': 'Dataset', 'paht_protocol': 'Protocol',
        'paht_temperature': 'Reported chamber test condition',
        'paht_temperature_basis': 'Temperature basis: reported chamber test condition; not verified specimen temperature',
        'paht_temperature_warning': 'The temperature label is the reported tensile-test/chamber condition after 30 min conditioning. Direct specimen temperature, calibration, sensor location, tolerance, stability and heating rate are unknown. Additional thermography from an earlier paper is not transferred.',
        'paht_process_warning': 'Selected rows are annealed Bambu Lab PAHT-CF, printed flat by FFF at ±45°. The article reports predrying at 80 °C for 12 h and annealing at 80 °C for 12 h, followed by cooling in a vacuum-sealed dehumidified container. Its all-specimens annealing wording conflicts with its annealed/non-annealed groups; only explicitly annealed rows are selected. Declared PA12/15 wt.% short carbon fiber is not an assay; 100% infill does not establish zero porosity. Actual moisture and numerical RH are unknown. The reported displacement rate is 10 mm/s, not a verified local strain rate or identified crosshead control channel; its unit is not corrected.',
        'paht_stress_warning': 'UTS is retained as reported. The central statistic is a reported median, not a mean. Engineering versus true stress, nominal versus actual stress-area basis, exact UTS extraction and aggregation details remain unverified.',
        'paht_sd_count_warning': 'Five specimens are reported per orientation × temperature × annealing group; 200 specimens cover the whole study. The separately reported standard deviation (SD) describes dispersion, not uncertainty of the median, SEM, a confidence interval, 68% coverage, bounds or a full uncertainty budget. Raw values, independence, exclusions and sample-versus-population SD convention are unverified. No CI is calculated from the count.',
        'paht_sd_unit_warning': 'Table A1 explicitly labels UTS in MPa but gives no unit in its separate Standard Deviation header. The SD unit MPa is inferred contextually from the associated UTS column; its Pa re-expression inherits that inference. Exact decimal unit scaling adds no measurement precision. Median and SD are displayed separately, without uncertainty endpoints.',
        'paht_geometry_warning': 'ISO 23529 Type 1, ISO 37 and ISO 527 are source assertions, not independently verified compliance. Figure 1 dimensions are drawing annotations, not measured dimensions or reconstructed stress areas; the inspected caption does not independently print their unit. Narrow width, actual stress area, gauge length and grip separation are unknown; the central straight length is not assigned as a strain gauge length.',
        'paht_scope_warning': 'These four conditions are one study/protocol, not four independent confirmations. This is a separate study from Ciganas, not a matched-condition replication or material ranking. Different commercial formulations, annealing, equipment, geometry, rates, temperature labels and summary statistics preclude pooling. No fit, interpolation, extrapolation, retention ranking, engineering allowable or universal bound is admitted.',
        'paht_version_warning': 'Publisher HTML was inspected on 2026-10-03; its reported update is 2 September 2026 03:21 CEST. Neither PDF version was inspected; HTML/PDF equivalence is not claimed. A separate reader reproduced the eight selected Table A1 numeric strings: this checks transcription, not experimental replication, measurement accuracy or scientific review. Raw data were not obtained.',
        'paht_rights_warning': 'Selected Table A1 facts are attributed to Zach and Dudescu (2025), DOI 10.3390/jcs9110624, under the article’s verified CC BY 4.0 license. Four rows were selected/reorganized; SI re-expression and original curator caveats were added. Source assets, supplier Table 1 and unselected groups are excluded; article rights do not establish rights to supplier works or later raw data, or imply author endorsement.',
        'paht_reported_display': 'Reported median and separate reported SD',
        'paht_reported_notice': 'Exact decimal source strings are preserved; printed digits do not establish measurement resolution or accuracy.',
        'paht_reported_median': 'Reported UTS median',
        'paht_reported_sd': 'Reported SD (MPa contextually inferred from UTS)',
        'paht_si_display': 'SI unit re-expression with the SD-unit inference retained',
        'paht_si_notice': '1 MPa = 1000000 Pa exactly. Scaling adds no precision and uses no geometry or thickness. For SD, the source unit MPa is contextual inference, not an explicitly printed header unit.',
        'paht_si_median': 'UTS median re-expressed in Pa',
        'paht_si_sd': 'SD re-expressed in Pa (source unit contextually inferred)',
        'paht_cell': 'Selected source cells', 'paht_material': 'Material and preparation metadata',
        'paht_method': 'Tensile protocol and nominal geometry', 'paht_conditions': 'Original temperature, humidity and other conditions',
        'paht_counts': 'Test counts and statistic metadata', 'paht_source_version': 'Inspected source version and limits',
        'paht_details': 'Original structured record details',
    },
    'zh': {
        'paht_classification': '来源报告 · 拉伸试验推导的汇总值 · 仅用于目录',
        'paht_identity': 'Bambu Lab PAHT-CF · 退火 · 平放 FFF · ±45° 取向 · 三维压力量纲',
        'paht_dataset': '数据集', 'paht_protocol': '试验方案',
        'paht_temperature': '来源报告的试验腔温度条件',
        'paht_temperature_basis': '温度依据：来源报告的试验腔条件；并非经核实的试样温度',
        'paht_temperature_warning': '温度标签为恒温处理 30 min 后报告的拉伸试验／试验腔条件。直接试样温度、校准、传感器位置、容差、稳定性和升温速率未知。不移用前一篇论文的额外热成像信息。',
        'paht_process_warning': '所选行为退火的 Bambu Lab PAHT-CF，以 ±45° 取向平放 FFF 打印。文章报告在 80 °C 预干燥 12 h、在 80 °C 退火 12 h，随后在真空密封的除湿容器中冷却。其所有试样均退火的措辞与退火／未退火分组存在矛盾；仅选择明确标为退火的行。标称 PA12／15 wt.% 短碳纤维并非实测成分；100% 填充不确立零孔隙率。实际含水量和数值相对湿度未知。报告的位移速率为 10 mm/s，既非已核实的局部应变率，也未确立为横梁控制通道；不更改其单位。',
        'paht_stress_warning': '按来源保留 UTS。中心统计量为报告的中位数，并非均值。工程应力或真实应力、标称或实际应力面积依据、精确 UTS 提取方式及汇总细节均未核实。',
        'paht_sd_count_warning': '来源报告每个取向 × 温度 × 退火状态组有五个试样，全研究共 200 个。单独报告的标准差（SD）表示离散程度，并非中位数的不确定度、均值标准误（SEM）、置信区间、68% 覆盖率、界限或完整不确定度预算。原始值、独立性、剔除情况以及样本／总体 SD 约定未核实。不根据样本数计算置信区间。',
        'paht_sd_unit_warning': '表 A1 的 UTS 表头明确标注 MPa，而单独的 Standard Deviation 表头未标单位。SD 的 MPa 单位由相关 UTS 列在上下文中推断；换算为 Pa 仍保留此推断。精确小数单位缩放不增加测量精度。中位数与 SD 分开显示，不计算不确定度端点。',
        'paht_geometry_warning': 'ISO 23529 Type 1、ISO 37 和 ISO 527 为来源陈述，并非独立核实的符合性。图 1 尺寸为图纸标注，不是实测试样尺寸或重建的应力面积；所查图注未独立印出其单位。窄段宽度、实际应力面积、标距和夹具间距未知；不将中央直段长度指定为应变标距。',
        'paht_scope_warning': '四个条件属于同一研究／方案，并非四次独立验证。这是与 Ciganas 不同的研究，并非同条件复现或材料排名。商业配方、退火、设备、几何、速率、温度标签及汇总统计量不同，不支持合并。不接纳拟合、插值、外推、保持率排名、工程许用值或普适界限。',
        'paht_version_warning': '出版商 HTML 于 2026-10-03 查阅，报告的更新时间为 2 September 2026 03:21 CEST。两个 PDF 版本均未查阅，不主张 HTML／PDF 等同。另一位读者复核了表 A1 选定的八个数值字符串；这仅检查转录，并非实验复现、测量准确度验证或科学审查。未取得原始数据。',
        'paht_rights_warning': '表 A1 选定事实归属于 Zach 和 Dudescu（2025），DOI 10.3390/jcs9110624，遵循文章已核实的 CC BY 4.0 许可。选取并重组了四行，添加 SI 重表达及原创整理说明。不包含来源图文资产、供应商表 1 或未选分组；文章许可不确立供应商作品或之后取得的原始数据的权利，也不表示作者背书。',
        'paht_reported_display': '报告的中位数与单独报告的 SD',
        'paht_reported_notice': '保留来源精确小数字符串；印出位数不确立测量分辨率或准确度。',
        'paht_reported_median': '报告的 UTS 中位数',
        'paht_reported_sd': '报告的 SD（MPa 由 UTS 上下文推断）',
        'paht_si_display': '保留 SD 单位推断的 SI 重表达',
        'paht_si_notice': '1 MPa = 1000000 Pa 为精确换算，不增加精度，也不使用几何或厚度。SD 的来源单位 MPa 是上下文推断，而非表头明确标注的单位。',
        'paht_si_median': '以 Pa 重表达的 UTS 中位数',
        'paht_si_sd': '以 Pa 重表达的 SD（来源单位由上下文推断）',
        'paht_cell': '选定来源单元格', 'paht_material': '材料与制备元数据',
        'paht_method': '拉伸方案与标称几何尺寸', 'paht_conditions': '原始温度、湿度及其他条件',
        'paht_counts': '试验次数与统计量元数据', 'paht_source_version': '已查阅的来源版本与限制',
        'paht_details': '原始结构化记录详情',
    },
    'ja': {
        'paht_classification': '出典報告 · 引張試験から得た要約値 · カタログ専用',
        'paht_identity': 'Bambu Lab PAHT-CF · アニーリング済み · 平置き FFF · ±45° 配向 · 三次元の圧力次元',
        'paht_dataset': 'データセット', 'paht_protocol': '試験手順',
        'paht_temperature': '報告された試験槽温度条件',
        'paht_temperature_basis': '温度の根拠：報告された試験槽条件であり、確認済みの試料温度ではない',
        'paht_temperature_warning': '温度ラベルは 30 min の温度調整後の引張試験／試験槽条件です。直接の試料温度、校正、センサー位置、許容差、安定性、昇温速度は不明です。先行論文の追加サーモグラフィー情報は転用しません。',
        'paht_process_warning': '選択行はアニーリング済み Bambu Lab PAHT-CF で、±45° 配向の平置き FFF 造形です。論文は 80 °C・12 h の予備乾燥と 80 °C・12 h のアニーリング、その後の真空密封除湿容器内での冷却を報告しています。全試料をアニーリングしたとの記述と処理／未処理の群分けには曖昧さがあり、明示された処理済み行だけを選びます。公称 PA12／15 wt.% 短炭素繊維は実測組成ではなく、100% 充填設定は空隙率ゼロを示しません。実際の含水量と数値 RH は不明です。報告変位速度 10 mm/s は確認済み局所ひずみ速度でも特定済みクロスヘッド制御量でもなく、単位を修正しません。',
        'paht_stress_warning': 'UTS は報告どおり保持します。中心統計量は報告された中央値であり、平均値ではありません。公称応力か真応力か、公称／実際の断面積基準、正確な UTS 抽出法、集計の詳細は未確認です。',
        'paht_sd_count_warning': '配向 × 温度 × アニーリング状態の各群で 5 試料、研究全体で 200 試料と報告されています。別に報告された標準偏差（SD）はばらつきを表し、中央値の不確かさ、SEM、信頼区間、68% 被覆、上下界、完全な不確かさ収支ではありません。生データ、独立性、除外、標本／母集団 SD の計算法は未確認です。試料数から信頼区間を計算しません。',
        'paht_sd_unit_warning': '表 A1 は UTS の MPa を明記しますが、別の Standard Deviation 見出しには単位がありません。SD の MPa は対応する UTS 列からの文脈的推定であり、Pa への再表現もこの推定を引き継ぎます。正確な十進単位換算は測定精度を増やしません。中央値と SD を別々に表示し、不確かさの端点は計算しません。',
        'paht_geometry_warning': 'ISO 23529 Type 1、ISO 37、ISO 527 は出典の主張であり、適合性は独立に確認していません。図 1 の寸法は図面注記で、実測寸法や再構成した応力断面積ではなく、確認したキャプションに独立した単位表記はありません。狭部幅、実際の応力断面積、標点距離、グリップ間隔は不明です。中央直線部の長さをひずみ標点距離にはしません。',
        'paht_scope_warning': '四条件は一つの研究／手順に属し、四つの独立した確認ではありません。Ciganas とは別の研究であり、同条件の再現実験や材料順位ではありません。市販配合、熱処理、装置、形状、速度、温度ラベル、要約統計量が異なるため、統合はできません。フィット、補間、外挿、保持率順位、設計許容値、普遍的な界は認めません。',
        'paht_version_warning': '出版社 HTML を 2026-10-03 に確認し、報告更新日時は 2 September 2026 03:21 CEST です。二つの PDF 版は未確認で、HTML／PDF の同一性は主張しません。別の読者が表 A1 の選択した 8 個の数値文字列を照合しました。これは転記確認であり、実験再現、測定精度の保証、科学的審査ではありません。生データは取得していません。',
        'paht_rights_warning': '表 A1 の選択情報は Zach と Dudescu（2025）、DOI 10.3390/jcs9110624 に帰属し、確認済みの記事 CC BY 4.0 ライセンスに従います。4 行を選択・再整理し、SI 再表現と独自の注意書きを追加しました。出典の図文資産、供給者の表 1、未選択群は除外します。記事の権利は供給者の著作物や後日得る生データの権利、著者の支持を意味しません。',
        'paht_reported_display': '報告中央値と別に報告された SD',
        'paht_reported_notice': '出典の十進文字列を正確に保持します。印字桁数は測定分解能や精度を示しません。',
        'paht_reported_median': '報告 UTS 中央値',
        'paht_reported_sd': '報告 SD（MPa は UTS の文脈から推定）',
        'paht_si_display': 'SD 単位の推定を保持した SI 再表現',
        'paht_si_notice': '1 MPa = 1000000 Pa は正確な換算です。精度を増やさず、形状や厚さは使用しません。SD の出典単位 MPa は文脈的推定であり、見出しに明記された単位ではありません。',
        'paht_si_median': 'Pa で再表現した UTS 中央値',
        'paht_si_sd': 'Pa で再表現した SD（出典単位は文脈から推定）',
        'paht_cell': '選択した出典セル', 'paht_material': '材料と準備のメタデータ',
        'paht_method': '引張手順と公称形状', 'paht_conditions': '元の温度・湿度および他の条件',
        'paht_counts': '試験数と統計量のメタデータ', 'paht_source_version': '確認した出典版と制約',
        'paht_details': '元の構造化記録の詳細',
    },
    'de': {
        'paht_classification': 'Quellenangabe · experimentell abgeleitete Zugprüfungszusammenfassung · nur für den Katalog',
        'paht_identity': 'Bambu Lab PAHT-CF · getempert · flach FFF-gedruckt · ±45°-Orientierung · 3D-Druckdimension',
        'paht_dataset': 'Datensatzgruppe', 'paht_protocol': 'Protokoll',
        'paht_temperature': 'Berichtete Kammerprüfbedingung',
        'paht_temperature_basis': 'Temperaturbasis: berichtete Kammerprüfbedingung; keine verifizierte Probentemperatur',
        'paht_temperature_warning': 'Die Temperatur bezeichnet die berichtete Zugprüfungs-/Kammerbedingung nach 30 min Konditionierung. Direkte Probentemperatur, Kalibrierung, Sensorposition, Toleranz, Stabilität und Heizrate sind unbekannt. Zusätzliche Thermografie aus einer früheren Publikation wird nicht übertragen.',
        'paht_process_warning': 'Ausgewählt sind getemperte Proben aus Bambu Lab PAHT-CF, flach per FFF mit ±45°-Orientierung gedruckt. Berichtet werden Vortrocknung bei 80 °C für 12 h, Tempern bei 80 °C für 12 h und Abkühlung im vakuumversiegelten, entfeuchteten Behälter. Die Aussage zum Tempern aller Proben widerspricht der Trennung in behandelte/unbehandelte Gruppen; nur ausdrücklich getemperte Zeilen werden gewählt. Deklariertes PA12/15 wt.% Kurzcarbonfasern ist kein analysierter Anteil; 100% Füllung belegt keine Nullporosität. Tatsächliche Feuchte und numerische RH sind unbekannt. Berichtete Verschiebungsgeschwindigkeit: 10 mm/s, keine verifizierte lokale Dehnrate oder identifizierte Traversenregelgröße; die Einheit wird nicht korrigiert.',
        'paht_stress_warning': 'UTS bleibt wie berichtet erhalten. Die zentrale Statistik ist ein berichteter Median, kein Mittelwert. Technische gegenüber wahrer Spannung, nominelle gegenüber tatsächlicher Bezugsfläche, genaue UTS-Auswertung und Aggregationsdetails sind ungeprüft.',
        'paht_sd_count_warning': 'Fünf Proben je Orientierung × Temperatur × Temperzustand werden berichtet; 200 Proben umfassen die gesamte Studie. Die separat berichtete Standardabweichung (SD) beschreibt Streuung, nicht Medianunsicherheit, SEM, Konfidenzintervall, 68%-Abdeckung, Grenzen oder ein vollständiges Unsicherheitsbudget. Rohwerte, Unabhängigkeit, Ausschlüsse und Stichproben-/Populations-SD-Konvention sind ungeprüft. Aus der Anzahl wird kein Konfidenzintervall berechnet.',
        'paht_sd_unit_warning': 'Tabelle A1 kennzeichnet UTS ausdrücklich mit MPa, aber die separate Überschrift Standard Deviation enthält keine Einheit. Die SD-Einheit MPa wird aus der zugehörigen UTS-Spalte kontextuell erschlossen; die Umrechnung in Pa übernimmt diese Annahme. Exakte dezimale Einheitenskalierung erhöht keine Messpräzision. Median und SD erscheinen getrennt, ohne Unsicherheitsendpunkte.',
        'paht_geometry_warning': 'ISO 23529 Type 1, ISO 37 und ISO 527 sind Quellenangaben, keine unabhängig verifizierte Normkonformität. Maße in Abbildung 1 sind Zeichnungsangaben, keine gemessenen Abmessungen oder rekonstruierten Spannungsquerschnitte; die eingesehene Bildunterschrift nennt ihre Einheit nicht separat. Schmale Breite, tatsächlicher Querschnitt, Messlänge und Griffabstand sind unbekannt; die mittlere gerade Länge wird nicht als Dehnungsmesslänge eingesetzt.',
        'paht_scope_warning': 'Vier Bedingungen gehören zu einer Studie/einem Protokoll, nicht zu vier unabhängigen Bestätigungen. Dies ist eine andere Studie als Ciganas, keine Wiederholung bei gleichen Bedingungen oder Materialrangfolge. Unterschiede in Handelsrezeptur, Tempern, Geräten, Geometrie, Geschwindigkeiten, Temperaturangaben und Statistik schließen Zusammenführung aus. Kein Fit, keine Interpolation, Extrapolation, Rangfolge des Festigkeitserhalts, Bemessungswerte oder universelle Grenzen sind zugelassen.',
        'paht_version_warning': 'Das Verlags-HTML wurde am 2026-10-03 geprüft; die berichtete Aktualisierung ist 2 September 2026 03:21 CEST. Keine der beiden PDF-Versionen wurde eingesehen; HTML/PDF-Gleichwertigkeit wird nicht behauptet. Ein zweiter Leser bestätigte die acht ausgewählten Zahlenzeichenfolgen aus Tabelle A1: Das prüft die Abschrift, nicht experimentelle Reproduktion, Messgenauigkeit oder wissenschaftliche Begutachtung. Rohdaten liegen nicht vor.',
        'paht_rights_warning': 'Ausgewählte Fakten aus Tabelle A1 werden Zach und Dudescu (2025), DOI 10.3390/jcs9110624, unter der verifizierten CC-BY-4.0-Lizenz des Artikels zugeschrieben. Vier Zeilen wurden ausgewählt/neu geordnet; SI-Umrechnung und eigene Vorbehalte kamen hinzu. Quellenmaterial, Lieferantentabelle 1 und nicht ausgewählte Gruppen sind ausgeschlossen. Artikelrechte belegen keine Rechte an Lieferantenwerken oder späteren Rohdaten und keine Zustimmung der Autoren.',
        'paht_reported_display': 'Berichteter Median und separat berichtete SD',
        'paht_reported_notice': 'Dezimale Quellenzeichenfolgen bleiben exakt erhalten; gedruckte Stellen belegen weder Messauflösung noch Genauigkeit.',
        'paht_reported_median': 'Berichteter UTS-Median',
        'paht_reported_sd': 'Berichtete SD (MPa kontextuell aus UTS erschlossen)',
        'paht_si_display': 'SI-Umrechnung mit beibehaltenem Vorbehalt zur SD-Einheit',
        'paht_si_notice': '1 MPa = 1000000 Pa gilt exakt. Skalierung erhöht keine Präzision und nutzt weder Geometrie noch Dicke. Die SD-Quelleneinheit MPa ist kontextuell erschlossen, nicht ausdrücklich in der Überschrift angegeben.',
        'paht_si_median': 'UTS-Median in Pa umgerechnet',
        'paht_si_sd': 'SD in Pa umgerechnet (Quelleneinheit kontextuell erschlossen)',
        'paht_cell': 'Ausgewählte Quellenzellen', 'paht_material': 'Material- und Vorbereitungsmetadaten',
        'paht_method': 'Zugprüfprotokoll und nominelle Geometrie', 'paht_conditions': 'Originale Temperatur-, Feuchte- und weitere Bedingungen',
        'paht_counts': 'Versuchszahlen und Statistikmetadaten', 'paht_source_version': 'Eingesehene Quellenversion und Grenzen',
        'paht_details': 'Originale strukturierte Datensatzdetails',
    },
}
